# Introduction to Python

**Python** merupakan bahasa pemrograman yang pertama kali diliris pada tahun 1991 dan dirancang oleh Guido Van Rossum. 
Bahasa pemrograman ini umum digunakan dalam bidang data science dan artificial intelligence. Hal tersebut disebabkan oleh sintaks (penulisan code) yang intuitif dan mudah dipelajari serta banyak resources yang mendukung pengembangan analisis data, visualisasi, machine learning dan sebagainya (Pandas, Numpy, Matplotlib dll.) [Python 3.10 Official Documentation](https://docs.python.org/3.10/).

## A. Jupyter Notebook

### A.1 Markdown Cell and Code Cell

Tipe cell dalam notebook:
1. Markdown -> untuk menulis teks dan narasi.
2. Code -> untuk menulis code dan dijalankan. 

### A.2 Command Mode and Edit Mode

Mode cell dalam notebook:
1. Command mode
    - `a` : add cell above 
    - `b` : add cell below 
    - `d` + `d` : delete selected cell 
    - `x` : cut selected cell 
    - `c` : copy selected cell 
    - `v` : paste selected cell 
    - `z` : undo 
    - `m` : change cell type to markdown 
    - `y` : change cell type to code
    - `enter` : enter Edit Mode
    - `h` : show keyboard shortcuts

2. Edit mode
    - `Ctrl + Enter`: eksekusi satu cell
    - `Esc`: Mengubah edit mode menjadi command mode

- Menulis tebal = **bold**
- Menulis miring = *italic*

## B. Python Variable

**Variable** adalah sebuah nama yang dipakai untuk menunjukkan sebuah nilai. Tanda `=` dipakai untuk membuat variable baru, proses ini sering disebut sebagai **assignment**.

In [3]:
# code
x=2

In [4]:
print(x)

2


Python merupakan bahasa pemrograman yang bersifat **case-sensitive** artinya penamaan variabel perlu diperhatikan. Misal penulisan variable `Toni` dengan awalan huruf `T` besar berbeda dengan yang diawali dengan huruf `t` kecil.

In [5]:
"Toni" == "toni"

False

Panduan pemberian nama variabel dalam bahasa Python : 
- Tidak boleh menggunakan angka di awal. 
- Menggunakan kombinasi dari huruf kapital (A-Z), huruf nomina (a-z), angka (0-9).
- Special character `!, $ , &, dll` tidak dapat digunakan dalam penamaan variabel.
- Bersifat case-sensitive sehingga penamaan variable `Python`, `PYTHON`, dan `python` adalah 3 variable yang berbeda
- Tidak boleh menggunakan keyword pada Python.

**Keywords** merupakan kumpulan kata kunci yang digunakan oleh Python sebagai nama sehingga tidak bisa digunakan untuk penamaan variabel, fungsi dan lainnya, contohnya `True`, `False`, dan `None`. Lengkapnya sebagai berikut : 

In [6]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

## C. Python Data Structure

Mengetahui struktur data Python pada umumnya dan menyesuaikan tipe data (*data formatting*).

### 1. String

Python memiliki tipe data berupa tulisan atau string sebagai objek `str`. Ada beberapa cara untuk membuat nilai string:

- menggunakan `''` (yaitu: `'Data Analyst'`)
- menggunakan `""` (yaitu : `"Hari ini adalah hari Jum'at"`)
- menggunakan `'''` atau `"""` (yaitu: `'''Budi berkata "Itu ada kegiatan Jum'at Bersih"'''`)

In [7]:
# code
nama = 'Resya'

In [8]:
# type(nama)

### 2. Number

Untuk menyimpan number, python memiliki dua tipe data asli yang disebut `int` dan `float`.
- `int` digunakan untuk menyimpan bilangan bulat (yaitu: 1,2,-3)
- `float` digunakan untuk menyimpan bilangan berkoma atau real (yaitu: 0.7, -1.8, -1000.0).

**Operasi Angka** \
Operator Aritmatika:
- `+` - Penjumlahan
- `-` - Pengurangan
- `*` - Perkalian
- `/` - Pembagian
- `//` - Floor Division (hasil pembagian dibulatkan ke bawah)
- `%` - Modulus (hasil sisa pembagian)
- `**` - Eksponen (Pangkat)

Operator Perbandingan:
- `<` - Lebih kecil dari (yaitu : a < b)
- `<=` - Lebih kecil atau sama dengan (yaitu : a <= b)
- `>` - Lebih besar dari (yaitu: a > b)
- `>=` - Lebih besar atau sama dengan (yaitu: a >= b)
- `==` - Sama dengan (yaitu: a == b)
- `!=` - Tidak Sama dengan (yaitu: a != b)

In [9]:
# code
x=4/2
type(x)

float

In [10]:
x=5/3
type(x)

float

In [11]:
# type int
x=-1*1
type(x)

int

In [12]:
# type float
x=2/1

### 3. Boolean

Boolean menyimpan nilai yang sangat sederhana dalam komputer dan pemrograman, `True` atau `False`.

**Operasi Boolean** \
Python menyediakan operator logika seperti:
- and (yaitu: a and b) -> Semua kondisi harus benar maka hasilnya True
- or (yaitu: a or c) -> Hanya salah satu kondisi benar maka hasilnya True
- not (yaitu: not a) -> Lawan kata

In [13]:
# Jenjang pendidikan tinggi bapak Rudi
undergraduate = True
master = True
phd = False

In [14]:
# Apakah bapak Rudi menyelesaikan pendidikan S1 DAN S2?
print(undergraduate and master)

# Apakah bapak Rudi menyelesaikan pendidikan S1 DAN S3?
print (undergraduate and phd)

# Apakah bapak Rudi menyelesaikan pendidikan S2 ATAU S3?
print(undergraduate or phd)

# Bapak Rudi TIDAK menyelesaikan pendidikan S1?
print (not undergraduate)

True
False
True
False


In [15]:
# type()
type (undergraduate)
type (phd)

bool

### 4. List

`list` digunakan untuk menyimpan beberapa nilai dalam python. Untuk membuatnya, cukup letakkan nilai di dalam tanda kurung (yaitu: `x = [10,08,2024]` )

**Operasi List**
- `data.append(2)` : tambahkan 2 ke data
- `data.remove(3)` : hapus 3 dari data

Selain operator yang dikenal sebelumnya, salah satu list yang paling berguna adalah dengan menerapkan fungsi agregasi seperti:
- `len(data)` : ekstrak panjang daftar
- `a in data` : memeriksa apakah nilai `a` ada di objek daftar `data`
- `max(data)` : mendapatkan nilai tertinggi dalam data
- `sum(data)` : mendapatkan jumlah nilai dalam data

Operasi lain yang harus diketahui dalam daftar adalah pengindeksan:
- `data[i]` : mengakses elemen ke-i dari data. **Zero Indexing Python.**

In [16]:
data = [2,"Mobile", True, 2.5]
data.append(2)
data.append(5)

In [17]:
# Zero Indexing Python.
data[2]
data[3]

2.5

In [18]:
type(data)

list

### 5. Dictionaries

Kami telah belajar tentang urutan dalam Python, tetapi sekarang kami akan mengganti persneling dan belajar tentang pemetaan dengan Python. Jika Anda terbiasa dengan bahasa lain, Anda dapat menganggap Kamus ini sebagai tabel hash.

Dictionary Python terdiri dari **key** dan kemudian **value** terkait. Nilai itu bisa berupa hampir semua objek Python.

**Membuat Dictionary**

Mari kita lihat bagaimana kita dapat membuat dictionary untuk mendapatkan pemahaman yang lebih baik tentang cara kerjanya!

In [19]:
# Make a dictionary with {} and : to signify a key and a value
my_dict = {"nama" : "resya",
"umur" : "20",
"hobi" : "menyanyi"}

In [20]:
# my_dict['nama']
my_dict["hobi"]

'menyanyi'

In [21]:
my_dict["nama"]

'resya'

In [22]:
# type(my_dict)
type(my_dict)

dict

## D. Introduction to Pandas Library

Library merupakan kumpulan alat-alat yang digunakan untuk membantu proses penyelesaian masalah.

- `pandas` merupakan salah satu library dalam bahasa pemrograma Python yang powerful sebagai tools analisis data. 

- `pandas` dapat mempermudah pengolahan data karena memiliki objek bernama **DataFrame**.

- Untuk informasi lebih lengkapnya dapat mengunjungi [official documentation](https://pandas.pydata.org/)

#### 1. Import Library

In [23]:
# Import Pandas + aliasing
import pandas as pd

In [24]:
# check versi pandas
pd.__version__

'2.1.4'

#### 2. Read Data

Kita dapat membaca data dengan format `.csv` melalui `.read_csv()`. Membaca data `sales.csv`. Sintaks : `pd.read_csv(path/data)`.

Silahkan baca data penjualan supermarket, [LEBIH LANJUT](https://www.kaggle.com/datasets/aungpyaeap/supermarket-sales). 

Apabila kita ingin set kolom pertama `Invoice ID` menjadi index dari dataframe. Caranya: menambahkan parameter index_col=0.

Parameter `index_col` dapat menerima beberapa nilai : 
- (0,1,2, dst) : menunjukkan index kolom yang dijadikan index baris. 
- `nama_kolom` : menunjukkan nama kolom yang dijadikan index baris. 
- `False` : Menggunakan index baris yang disediakan oleh `pandas` atau (default). 
- Beberapa parameter dalam method `.read_csv()`, dokumentasi selengkapnya ada [di sini](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). 

In [25]:
# baca data\sales.csv simpan sales
sales = pd.read_csv("data\sales.csv")
sales.head()

Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428      A     Yangon        Member  Female   
1  226-31-3081      C  Naypyitaw        Normal  Female   
2  631-41-3108      A     Yangon        Normal    Male   
3  123-19-1176      A     Yangon        Member    Male   
4  373-73-7910      A     Yangon        Normal    Male   

             Product line  Unit price  Quantity   Tax 5%     Total       Date  \
0       Health and beauty       74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories       15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle       46.33         7  16.2155  340.5255   3/3/2019   
3       Health and beauty       58.22         8  23.2880  489.0480  1/27/2019   
4       Sports and travel       86.31         7  30.2085  634.3785   2/8/2019   

    Time      Payment      cogs  gross margin percentage  gross income  Rating  
0  13:08      Ewallet  475.7753                  9.89011       47.0547     9.1  
1  10:29         Cash   69.5240                  9.89011        6.8760     9.6  
2  13:23  Credit card  295.1221                  9.89011       29.1879     7.4  
3  20:33      Ewallet  423.8416                  9.89011       41.9184     8.4  
4  10:37      Ewallet  549.7947                  9.89011       54.3753     5.3

In [26]:
sales = pd.read_csv("data\sales.csv", index_col=0)


In [27]:
# type(sales)
type(sales)

pandas.core.frame.DataFrame

In [28]:
# Melihat 5 data teratas


Attribute information
- `Invoice id`: Computer generated sales slip invoice identification number
- `Branch`: Branch of supercenter (3 branches are available identified by A, B and C).
- `City`: Location of supercenters
- `Customer type`: Type of customers, recorded by Members for customers using member card and Normal for without member card.
- `Gender`: Gender type of customer
- `Product line`: General item categorization groups - Electronic accessories, Fashion accessories, Food and beverages, Health and beauty, - Home and lifestyle, Sports and travel
- `Unit price`: Price of each product in $
- `Quantity`: Number of products purchased by customer
- `Tax`: 5% tax fee for customer buying
- `Total`: Total price including tax
- `Date`: Date of purchase (Record available from January 2019 to March 2019)
- `Time`: Purchase time (10am to 9pm)
- `Payment`: Payment used by customer for purchase (3 methods are available – Cash, Credit card and Ewallet)
- `COGS`: Cost of goods sold
- `Gross margin percentage`: Gross margin percentage
- `Gross income`: Gross income
- `Rating`: Customer stratification rating on their overall shopping experience (On a scale of 1 to 10)

**Review Materi**

Berdasarkan pada berbagai materi penulisan code python di atas, manakah di antara ke-5 kode program ini yang tidak menghasilkan error ketika dijalankan?
- [ ] `import Pandas as pd`
- [x] `print(100**2)`
- [ ] `pd.read_csv("data\sales.csv", index_col = false)`.
- [ ] `True = 1`

In [29]:
import Pandas as pd

ModuleNotFoundError: No module named 'Pandas'

In [ ]:
import pandas as pd

In [ ]:
print(100**2)

10000


In [43]:
pd.read_csv("data\sales.csv", index_col = false)

NameError: name 'false' is not defined

In [49]:
pd.read_csv("data\sales.csv", index_col = False)

Invoice ID Branch       City Customer type  Gender  \
0    750-67-8428      A     Yangon        Member  Female   
1    226-31-3081      C  Naypyitaw        Normal  Female   
2    631-41-3108      A     Yangon        Normal    Male   
3    123-19-1176      A     Yangon        Member    Male   
4    373-73-7910      A     Yangon        Normal    Male   
..           ...    ...        ...           ...     ...   
995  233-67-5758      C  Naypyitaw        Normal    Male   
996  303-96-2227      B   Mandalay        Normal  Female   
997  727-02-1313      A     Yangon        Member    Male   
998  347-56-2442      A     Yangon        Normal    Male   
999  849-09-3807      A     Yangon        Member  Female   

               Product line  Unit price  Quantity   Tax 5%      Total  \
0         Health and beauty       74.69         7  26.1415   548.9715   
1    Electronic accessories       15.28         5   3.8200    80.2200   
2        Home and lifestyle       46.33         7  16.2155   340.5255   
3         Health and beauty       58.22         8  23.2880   489.0480   
4         Sports and travel       86.31         7  30.2085   634.3785   
..                      ...         ...       ...      ...        ...   
995       Health and beauty       40.35         1   2.0175    42.3675   
996      Home and lifestyle       97.38        10  48.6900  1022.4900   
997      Food and beverages       31.84         1   1.5920    33.4320   
998      Home and lifestyle       65.82         1   3.2910    69.1110   
999     Fashion accessories       88.34         7  30.9190   649.2990   

          Date   Time      Payment      cogs  gross margin percentage  \
0     1/5/2019  13:08      Ewallet  475.7753                  9.89011   
1     3/8/2019  10:29         Cash   69.5240                  9.89011   
2     3/3/2019  13:23  Credit card  295.1221                  9.89011   
3    1/27/2019  20:33      Ewallet  423.8416                  9.89011   
4     2/8/2019  10:37      Ewallet  549.7947                  9.89011   
..         ...    ...          ...       ...                      ...   
995  1/29/2019  13:46      Ewallet   36.7185                  9.89011   
996   3/2/2019  17:16      Ewallet  886.1580                  9.89011   
997   2/9/2019  13:22         Cash   28.9744                  9.89011   
998  2/22/2019  15:33         Cash   59.8962                  9.89011   
999  2/18/2019  13:28         Cash  562.7258                  9.89011   

     gross income  Rating  
0         47.0547     9.1  
1          6.8760     9.6  
2         29.1879     7.4  
3         41.9184     8.4  
4         54.3753     5.3  
..            ...     ...  
995        3.6315     6.2  
996       87.6420     4.4  
997        2.8656     7.7  
998        5.9238     4.1  
999       55.6542     6.6  

[1000 rows x 17 columns]

In [ ]:
True = 1

SyntaxError: cannot assign to True (1770609971.py, line 1)

In [ ]:
true = 1

#### 3. Check Tipe Data `pandas`

In [30]:
# code
sales.dtypes

Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

- Dataframe merupakan tabel/data tabular dua dimensi yaitu baris dan kolom.
- Dataframe terdiri dari beberapa **Series** (kolom).
- Dalam satu series harus memiliki tipe data yang sama.
- `pandas` akan menentukan tipe data dari masing-masing Series, tapi hasil dari pandas tidak selalu benar.



Berikut rangkuman tipe data `pandas`:

| Pandas dtype  | Python type  | Usage                                        |
|---------------|--------------|----------------------------------------------|
| object        | str or mixed | Text or mixed numeric and non-numeric values |
| int64         | int          | Integer numbers                              |
| float64       | float        | Floating point numbers                       |
| bool          | bool         | True/False values                            |
| datetime64    | NA           | Date and time values                         |
| timedelta[ns] | NA           | Differences between two datetimes            |
| category      | NA           | Finite list of text values                   |

Referensi: [Overview of Pandas Data Types](https://pbpython.com/pandas_dtypes.html)

In [31]:
# Tipe data setiap kolom / series  `.dtypes`
sales.dtypes

Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

#### 4. Data Formatting

Data formatting merupakan proses untuk mengubah format suatu data menjadi format sebenarnya. Kita dapat menggunakan `astype()`. Contoh 
Sintaks : 

`df['column_name'] = df['column_name'].astype('new_data_types')`

In [32]:
#sales.nunique()
sales.nunique()

Branch                       3
City                         3
Customer type                2
Gender                       2
Product line                 6
Unit price                 943
Quantity                    10
Tax 5%                     990
Total                      990
Date                        89
Time                       506
Payment                      3
cogs                       990
gross margin percentage     31
gross income               990
Rating                      61
dtype: int64

Data yang Perlu disesuaikan :
- `Branch` = `category`
- `City` = `category`
- `Customer type` = `category`
- `Gender` = `category`
- `Product line` = `category`
- `Date` = `datetime64[ns]`
- `Time` = `datetime64[ns]`
- `Payment` = `category`

In [33]:
# Copy dulu datanya agar data aslinya tidak berubah ke df 
df = sales.copy()
df.head(3)

Branch       City Customer type  Gender            Product line  \
Invoice ID                                                                    
750-67-8428      A     Yangon        Member  Female       Health and beauty   
226-31-3081      C  Naypyitaw        Normal  Female  Electronic accessories   
631-41-3108      A     Yangon        Normal    Male      Home and lifestyle   

             Unit price  Quantity   Tax 5%     Total      Date   Time  \
Invoice ID                                                              
750-67-8428       74.69         7  26.1415  548.9715  1/5/2019  13:08   
226-31-3081       15.28         5   3.8200   80.2200  3/8/2019  10:29   
631-41-3108       46.33         7  16.2155  340.5255  3/3/2019  13:23   

                 Payment      cogs  gross margin percentage  gross income  \
Invoice ID                                                                  
750-67-8428      Ewallet  475.7753                  9.89011       47.0547   
226-31-3081         Cash   69.5240                  9.89011        6.8760   
631-41-3108  Credit card  295.1221                  9.89011       29.1879   

             Rating  
Invoice ID           
750-67-8428     9.1  
226-31-3081     9.6  
631-41-3108     7.4

In [34]:
# df['Branch'] = df['Branch'].astype('category')
df["Branch"].astype("category")
df['Branch'].astype('category')

# df.dtypes

Invoice ID
750-67-8428    A
226-31-3081    C
631-41-3108    A
123-19-1176    A
373-73-7910    A
              ..
233-67-5758    C
303-96-2227    B
727-02-1313    A
347-56-2442    A
849-09-3807    A
Name: Branch, Length: 1000, dtype: category
Categories (3, object): ['A', 'B', 'C']

In [35]:
df['Branch'] = df['Branch'].astype('category')
df.dtypes

Branch                     category
City                         object
Customer type                object
Gender                       object
Product line                 object
Unit price                  float64
Quantity                      int64
Tax 5%                      float64
Total                       float64
Date                         object
Time                         object
Payment                      object
cogs                        float64
gross margin percentage     float64
gross income                float64
Rating                      float64
dtype: object

In [36]:
df['City'] = df['City'].astype('category')
df['Customer type'] = df['Customer type'].astype('category')
df['Gender'] = df['Gender'].astype('category')
df['Product line'] = df['Product line'].astype('category')
df['Date'] = df['Date'].astype('datetime64[ns]')
df['Time'] = df['Time'].astype('datetime64[ns]')
df['Payment'] = df['Payment'].astype('category')

C:\Users\Naresya Wijaya\AppData\Local\Temp\ipykernel_16724\3658447013.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Time'] = df['Time'].astype('datetime64[ns]')


In [37]:
df.dtypes

Branch                           category
City                             category
Customer type                    category
Gender                           category
Product line                     category
Unit price                        float64
Quantity                            int64
Tax 5%                            float64
Total                             float64
Date                       datetime64[ns]
Time                       datetime64[ns]
Payment                          category
cogs                              float64
gross margin percentage           float64
gross income                      float64
Rating                            float64
dtype: object

#### 5. Feature Engineering - Datetime Partition (**Complement**)

Kegunaan sebuah kolom menjadi tipe data `datetime64` adalah dapat mengambil bagian waktu informasi waktu secara lebih spesifik dan digunakan untuk analisis harian, mingguan, bulanan, dan sebagainya. 

**Date component (numeric)**
- `.dt.year` : tahun
- `.dt.month` : bulan (dalam angka)
- `.dt.day` : tanggal (dalam angka)
- `.dt.dayofweek` : hari ke berapa dalam seminggu (0-6)

**Data component (period)**
- `.dt.to_period('Y')`: periode quarter (12 bulanan)
- `.dt.to_period('Q')`: periode quarter (3 bulanan)
- `.dt.to_period('M')`: periode bulanan (1 bulanan)
- `.dt.to_period('D')`: periode harian (1 harian)


**Date component (string)**
- `.dt.month_name()` : nama bulan
- `.dt.day_name()` : nama hari


**Time component**
- `.dt.hour` : jam
- `.dt.minute` : menit
- `.dt.second` : detik

> [Dokumentasi: datetime properties](https://pandas.pydata.org/pandas-docs/stable/reference/series.html#datetimelike-properties)

In [38]:
# Menambahkan kolom Tahun, Bulan, Nama Hari dan simpan ke category
df['Date'].dt.year

Invoice ID
750-67-8428    2019
226-31-3081    2019
631-41-3108    2019
123-19-1176    2019
373-73-7910    2019
               ... 
233-67-5758    2019
303-96-2227    2019
727-02-1313    2019
347-56-2442    2019
849-09-3807    2019
Name: Date, Length: 1000, dtype: int32

In [39]:
df['Date'].dt.day_name()

Invoice ID
750-67-8428    Saturday
226-31-3081      Friday
631-41-3108      Sunday
123-19-1176      Sunday
373-73-7910      Friday
                 ...   
233-67-5758     Tuesday
303-96-2227    Saturday
727-02-1313    Saturday
347-56-2442      Friday
849-09-3807      Monday
Name: Date, Length: 1000, dtype: object

In [40]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day_name()
df['Day of week'] = df['Date'].dt.dayofweek

df['Date'] = df['Date'].astype('datetime64[ns]')
df['Day'] = df['Day'].astype('category')

In [41]:
# cek 5 data teratas
df.head(5)

Branch       City Customer type  Gender            Product line  \
Invoice ID                                                                    
750-67-8428      A     Yangon        Member  Female       Health and beauty   
226-31-3081      C  Naypyitaw        Normal  Female  Electronic accessories   
631-41-3108      A     Yangon        Normal    Male      Home and lifestyle   
123-19-1176      A     Yangon        Member    Male       Health and beauty   
373-73-7910      A     Yangon        Normal    Male       Sports and travel   

             Unit price  Quantity   Tax 5%     Total       Date  \
Invoice ID                                                        
750-67-8428       74.69         7  26.1415  548.9715 2019-01-05   
226-31-3081       15.28         5   3.8200   80.2200 2019-03-08   
631-41-3108       46.33         7  16.2155  340.5255 2019-03-03   
123-19-1176       58.22         8  23.2880  489.0480 2019-01-27   
373-73-7910       86.31         7  30.2085  634.3785 2019-02-08   

                           Time      Payment      cogs  \
Invoice ID                                               
750-67-8428 2024-09-22 13:08:00      Ewallet  475.7753   
226-31-3081 2024-09-22 10:29:00         Cash   69.5240   
631-41-3108 2024-09-22 13:23:00  Credit card  295.1221   
123-19-1176 2024-09-22 20:33:00      Ewallet  423.8416   
373-73-7910 2024-09-22 10:37:00      Ewallet  549.7947   

             gross margin percentage  gross income  Rating  Year  Month  \
Invoice ID                                                                
750-67-8428                  9.89011       47.0547     9.1  2019      1   
226-31-3081                  9.89011        6.8760     9.6  2019      3   
631-41-3108                  9.89011       29.1879     7.4  2019      3   
123-19-1176                  9.89011       41.9184     8.4  2019      1   
373-73-7910                  9.89011       54.3753     5.3  2019      2   

                  Day  Day of week  
Invoice ID                          
750-67-8428  Saturday            5  
226-31-3081    Friday            4  
631-41-3108    Sunday            6  
123-19-1176    Sunday            6  
373-73-7910    Friday            4

In [42]:
df.dtypes

Branch                           category
City                             category
Customer type                    category
Gender                           category
Product line                     category
Unit price                        float64
Quantity                            int64
Tax 5%                            float64
Total                             float64
Date                       datetime64[ns]
Time                       datetime64[ns]
Payment                          category
cogs                              float64
gross margin percentage           float64
gross income                      float64
Rating                            float64
Year                                int32
Month                               int32
Day                              category
Day of week                         int32
dtype: object

## E. Data Cleansing

### Missing Value

##### 1. Check Missing Value 

In [43]:
# Read data, index = baris, index col = kolom
miss_dup = pd.read_csv("data/sales_missing_duplicate.csv")
miss_dup

Invoice ID Branch       City Customer type  Gender  \
0   750-67-8428      A     Yangon        Member  Female   
1   226-31-3081      C  Naypyitaw        Normal  Female   
2   631-41-3108      A     Yangon        Normal    Male   
3   123-19-1176    NaN     Yangon        Member    Male   
4   373-73-7910    NaN     Yangon        Normal    Male   
5   699-14-3026      C  Naypyitaw        Normal    Male   
6   355-53-5943      A     Yangon        Member  Female   
7   315-22-5665      C  Naypyitaw        Normal  Female   
8   665-32-9167      A     Yangon        Member  Female   
9   692-92-5582      B   Mandalay        Member  Female   
10  351-62-0822      B   Mandalay        Member  Female   
11  529-56-3974      B   Mandalay        Member    Male   
12  365-64-0515      A     Yangon        Normal  Female   
13  252-56-2699      A     Yangon        Normal    Male   
14  829-34-3910    NaN     Yangon        Normal  Female   
15  299-46-1805      B   Mandalay        Member  Female   
16  656-95-9349      A     Yangon        Member  Female   
17  765-26-6951      A     Yangon        Normal    Male   
18  329-62-1586      A     Yangon        Normal    Male   
19  319-50-3348      B   Mandalay        Normal  Female   
20  319-50-3348      B   Mandalay        Normal  Female   
21  373-73-7910      A     Yangon        Normal    Male   

              Product line  Unit price  Quantity   Tax 5%     Total  \
0        Health and beauty         NaN         7  26.1415  548.9715   
1   Electronic accessories       15.28         5   3.8200   80.2200   
2       Home and lifestyle       46.33         7  16.2155  340.5255   
3        Health and beauty       58.22         8  23.2880  489.0480   
4        Sports and travel         NaN         7  30.2085  634.3785   
5   Electronic accessories       85.39         7  29.8865  627.6165   
6   Electronic accessories       68.84         6  20.6520  433.6920   
7       Home and lifestyle       73.56        10  36.7800  772.3800   
8        Health and beauty       36.26         2   3.6260   76.1460   
9       Food and beverages       54.84         3   8.2260  172.7460   
10     Fashion accessories       14.48         4   2.8960   60.8160   
11  Electronic accessories       25.51         4   5.1020  107.1420   
12  Electronic accessories       46.95         5  11.7375  246.4875   
13      Food and beverages       43.19        10  21.5950  453.4950   
14       Health and beauty         NaN        10  35.6900  749.4900   
15       Sports and travel       93.72         6  28.1160  590.4360   
16       Health and beauty       68.93         7  24.1255  506.6355   
17       Sports and travel       72.61         6  21.7830  457.4430   
18      Food and beverages         NaN         3   8.2005  172.2105   
19      Home and lifestyle       40.30         2   4.0300   84.6300   
20      Home and lifestyle       40.30         2   4.0300   84.6300   
21       Sports and travel         NaN         7  30.2085  634.3785   

         Date   Time      Payment      cogs  gross margin percentage  \
0    1/5/2019  13:08      Ewallet  475.7753                  9.89011   
1    3/8/2019  10:29         Cash   69.5240                  9.89011   
2    3/3/2019  13:23  Credit card  295.1221                  9.89011   
3   1/27/2019  20:33      Ewallet  423.8416                  9.89011   
4    2/8/2019  10:37      Ewallet  549.7947                  9.89011   
5   3/25/2019  18:30      Ewallet  543.9343                  9.89011   
6   2/25/2019  14:36      Ewallet  375.8664                  9.89011   
7   2/24/2019  11:38      Ewallet  669.3960                  9.89011   
8   1/10/2019  17:15  Credit card   65.9932                  9.89011   
9   2/20/2019  13:27  Credit card  149.7132                  9.89011   
10   2/6/2019  18:07      Ewallet   52.7072                  9.89011   
11   3/9/2019  17:03         Cash   92.8564                  9.89011   
12  2/12/2019  10:25      Ewallet  213.6225                  9.89011   
13   

In [44]:
# cek missing value .info()
miss_dup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Invoice ID               22 non-null     object 
 1   Branch                   19 non-null     object 
 2   City                     22 non-null     object 
 3   Customer type            22 non-null     object 
 4   Gender                   22 non-null     object 
 5   Product line             22 non-null     object 
 6   Unit price               17 non-null     float64
 7   Quantity                 22 non-null     int64  
 8   Tax 5%                   22 non-null     float64
 9   Total                    22 non-null     float64
 10  Date                     22 non-null     object 
 11  Time                     22 non-null     object 
 12  Payment                  22 non-null     object 
 13  cogs                     22 non-null     float64
 14  gross margin percentage  22 

In [45]:
# cek missing value .isna().sum()
miss_dup.isna().sum()

Invoice ID                 0
Branch                     3
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 5
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     3
dtype: int64

##### 2. Treatment Missing Value

Terdapat beberapa cara umum untuk menangani missing values :

- Hapus baris atau kolom: Menggunakan metode `dropna()` dengan ambang batas yang wajar untuk menghapus setiap baris yang berisi nilai missing, NA < 5%
- Imputasi: Mengisi nilai NA dengan sebuah nilai

**Treatment Drop yang Missing Value**

- `.dropna(how='any')` : Hapus baris ketika memiliki **minimal 1 kolom** nilai missing. 
- `.dropna(how='all')` : Hapus baris ketika memiliki **semua kolom** nilai missing.
- `.dropna(tresh='...')`: Hapus baris ketika memiliki **angka yang dimasukan** nilai missing.

In [46]:
# code
miss_dup.dropna().isna().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

In [47]:
miss_dup.dropna().info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 2 to 20
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Invoice ID               14 non-null     object 
 1   Branch                   14 non-null     object 
 2   City                     14 non-null     object 
 3   Customer type            14 non-null     object 
 4   Gender                   14 non-null     object 
 5   Product line             14 non-null     object 
 6   Unit price               14 non-null     float64
 7   Quantity                 14 non-null     int64  
 8   Tax 5%                   14 non-null     float64
 9   Total                    14 non-null     float64
 10  Date                     14 non-null     object 
 11  Time                     14 non-null     object 
 12  Payment                  14 non-null     object 
 13  cogs                     14 non-null     float64
 14  gross margin percentage  14 non-n

In [48]:
miss_dup=miss_dup.dropna(how='any')

In [49]:
miss_dup.dropna(how='any')

Invoice ID Branch       City Customer type  Gender  \
2   631-41-3108      A     Yangon        Normal    Male   
5   699-14-3026      C  Naypyitaw        Normal    Male   
6   355-53-5943      A     Yangon        Member  Female   
7   315-22-5665      C  Naypyitaw        Normal  Female   
8   665-32-9167      A     Yangon        Member  Female   
9   692-92-5582      B   Mandalay        Member  Female   
10  351-62-0822      B   Mandalay        Member  Female   
11  529-56-3974      B   Mandalay        Member    Male   
12  365-64-0515      A     Yangon        Normal  Female   
15  299-46-1805      B   Mandalay        Member  Female   
16  656-95-9349      A     Yangon        Member  Female   
17  765-26-6951      A     Yangon        Normal    Male   
19  319-50-3348      B   Mandalay        Normal  Female   
20  319-50-3348      B   Mandalay        Normal  Female   

              Product line  Unit price  Quantity   Tax 5%     Total  \
2       Home and lifestyle       46.33         7  16.2155  340.5255   
5   Electronic accessories       85.39         7  29.8865  627.6165   
6   Electronic accessories       68.84         6  20.6520  433.6920   
7       Home and lifestyle       73.56        10  36.7800  772.3800   
8        Health and beauty       36.26         2   3.6260   76.1460   
9       Food and beverages       54.84         3   8.2260  172.7460   
10     Fashion accessories       14.48         4   2.8960   60.8160   
11  Electronic accessories       25.51         4   5.1020  107.1420   
12  Electronic accessories       46.95         5  11.7375  246.4875   
15       Sports and travel       93.72         6  28.1160  590.4360   
16       Health and beauty       68.93         7  24.1255  506.6355   
17       Sports and travel       72.61         6  21.7830  457.4430   
19      Home and lifestyle       40.30         2   4.0300   84.6300   
20      Home and lifestyle       40.30         2   4.0300   84.6300   

         Date   Time      Payment      cogs  gross margin percentage  \
2    3/3/2019  13:23  Credit card  295.1221                  9.89011   
5   3/25/2019  18:30      Ewallet  543.9343                  9.89011   
6   2/25/2019  14:36      Ewallet  375.8664                  9.89011   
7   2/24/2019  11:38      Ewallet  669.3960                  9.89011   
8   1/10/2019  17:15  Credit card   65.9932                  9.89011   
9   2/20/2019  13:27  Credit card  149.7132                  9.89011   
10   2/6/2019  18:07      Ewallet   52.7072                  9.89011   
11   3/9/2019  17:03         Cash   92.8564                  9.89011   
12  2/12/2019  10:25      Ewallet  213.6225                  9.89011   
15  1/15/2019  16:19         Cash  511.7112                  9.89011   
16  3/11/2019  11:03  Credit card  439.0841                  9.89011   
17   1/1/2019  10:39  Credit card  396.4506                  9.89011   
19  3/11/2019  15:30      Ewallet   73.3460                  9.89011   
20  3/11/2019  15:30      Ewallet   73.3460                  9.89011   

    gross income  Rating  
2        29.1879     7.4  
5        53.7957     4.1  
6        37.1736     5.8  
7        66.2040     8.0  
8         6.5268     7.2  
9        14.8068     5.9  
10        5.2128     4.5  
11        9.1836     6.8  
12       21.1275     7.1  
15       50.6088     4.5  
16       43.4259     4.6  
17       39.2094     6.9  
19        7.2540     4.4  
20        7.2540     4.4

In [50]:
#.dropna(how='any')
miss_dup.dropna(how='any').info()
#.dropna(how='all')
miss_dup.dropna(how='all').info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 2 to 20
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Invoice ID               14 non-null     object 
 1   Branch                   14 non-null     object 
 2   City                     14 non-null     object 
 3   Customer type            14 non-null     object 
 4   Gender                   14 non-null     object 
 5   Product line             14 non-null     object 
 6   Unit price               14 non-null     float64
 7   Quantity                 14 non-null     int64  
 8   Tax 5%                   14 non-null     float64
 9   Total                    14 non-null     float64
 10  Date                     14 non-null     object 
 11  Time                     14 non-null     object 
 12  Payment                  14 non-null     object 
 13  cogs                     14 non-null     float64
 14  gross margin percentage  14 non-n

In [51]:
# thresh = 15, minimal harus ada 15 kolom yang TIDAK missing agar dipertahankan
# alias apabila missing value cuma 1 kolom akan dipertahankan 
miss_dup.dropna(thresh=15).isna().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

**Treatment Imputasi yang Missing Value**

Imputasi dipilih apabila kita ingin mengisi nilai dari sebuah missing value melalui metode `.fillna()`. Informasi untuk mengisi nilai yang hilang memiliki banyak cara, baik berupa pengecekkan history, pengetahuan bisnis, metode statistik dan sebagainya. 

Untuk Kolom Numerik : 
- Isi dengan pusat data seperti `mean` atau `median`.
- Isi dengan model prediktif (regresi).

Untuk Kolom Kategorikal : 
- Isi dengan pusta data `modus` (`mode`).
- Isi dengan model prediktif (klasifikasi).

In [52]:
miss_dup.isna().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

Data yang Missing Value : 
1. `Branch` : 3 Kolom -> **object / kategorikal**
2. `Unit price` : 5 kolom -> **pengetahuan bisnis**
3. `Rating` : 3 kolom -> **numerik**

In [53]:
# 1. Branch dengan .mode()
input_branch = miss_dup['Branch'].mode()[0]
input_branch

'A'

In [54]:
input_branch = miss_dup['Branch'].mode()[0]
input_branch


'A'

In [55]:
# .fillna(value='...')
miss_dup['Branch'] = miss_dup['Branch'].fillna(value=input_branch)
miss_dup.isna().sum()

C:\Users\Naresya Wijaya\AppData\Local\Temp\ipykernel_16724\1994261019.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  miss_dup['Branch'] = miss_dup['Branch'].fillna(value=input_branch)


Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

In [56]:
miss_dup['Branch']

2     A
5     C
6     A
7     C
8     A
9     B
10    B
11    B
12    A
15    B
16    A
17    A
19    B
20    B
Name: Branch, dtype: object

In [57]:
# 2. Unit price dengan pengetahuan bisnis
"""
    Total Sales = Total - Tax 5%
    Total Sales = Unit price x Quantity
    Total Sales / Quantity = Unit price
"""

total_sales = miss_dup['Total'] - miss_dup['Tax 5%']
miss_dup['Unit price'] = total_sales / miss_dup['Quantity']
miss_dup.isna().sum()

C:\Users\Naresya Wijaya\AppData\Local\Temp\ipykernel_16724\979884172.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  miss_dup['Unit price'] = total_sales / miss_dup['Quantity']


Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

In [58]:
# 3. Rating dengan .mean()
input_rating = miss_dup['Rating'].mean()


In [59]:
# code
miss_dup['Rating'] = miss_dup['Rating'].fillna(value=input_rating)
miss_dup.isna().sum()

C:\Users\Naresya Wijaya\AppData\Local\Temp\ipykernel_16724\4253690220.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  miss_dup['Rating'] = miss_dup['Rating'].fillna(value=input_rating)


Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

### Duplicate Data

##### 1. Check Duplicated Value 

Untuk melakukan pengecekan terhadap ada atau tidaknya data yang duplikat, kita dapat menggunakan method `duplicated()`.

In [60]:
# code
miss_dup.duplicated().sum()

1

In [61]:
miss_dup.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 2 to 20
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Invoice ID               14 non-null     object 
 1   Branch                   14 non-null     object 
 2   City                     14 non-null     object 
 3   Customer type            14 non-null     object 
 4   Gender                   14 non-null     object 
 5   Product line             14 non-null     object 
 6   Unit price               14 non-null     float64
 7   Quantity                 14 non-null     int64  
 8   Tax 5%                   14 non-null     float64
 9   Total                    14 non-null     float64
 10  Date                     14 non-null     object 
 11  Time                     14 non-null     object 
 12  Payment                  14 non-null     object 
 13  cogs                     14 non-null     float64
 14  gross margin percentage  14 non-n

> Terdapat dua baris yang memiliki informasi sama persis (duplikasi).

##### 2. Treatment Duplicated Value

In [62]:
# .drop_duplicates()
miss_dup = miss_dup.drop_duplicates()

In [63]:
# cek data .info()
miss_dup.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 2 to 19
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Invoice ID               13 non-null     object 
 1   Branch                   13 non-null     object 
 2   City                     13 non-null     object 
 3   Customer type            13 non-null     object 
 4   Gender                   13 non-null     object 
 5   Product line             13 non-null     object 
 6   Unit price               13 non-null     float64
 7   Quantity                 13 non-null     int64  
 8   Tax 5%                   13 non-null     float64
 9   Total                    13 non-null     float64
 10  Date                     13 non-null     object 
 11  Time                     13 non-null     object 
 12  Payment                  13 non-null     object 
 13  cogs                     13 non-null     float64
 14  gross margin percentage  13 non-n

## F. Exploratory Data Analysis (EDA) - Basic

Exploratory Data Analysis (**EDA**) mengacu pada proses melakukan investigasi dan mencari informasi penting dalam suatu data. Kita dapat melihat struktur/bentuk data, gambaran statistik data dan sebagainya. 

**Method vs. Atribut**
- Secara penulisan/sintaks:
    - Method menggunakan tanda kurung `()`
    - Atribut **tidak** menggunakan tanda kurung

- Secara kegunaan:
    - Method memiliki nilai parameter yang dapat disesuaikan
    - Atribute **tidak** ada parameter

Library `pandas` memiliki method dan attribute untuk melakukan EDA : 
- `.head()` and `.tail()`
- `.describe()`
- `.dtypes`
- `.info()`

#### 1. `.head()` dan `.tail()`

- `.head()` digunakan untuk melihat data teratas (default = 5)
- `.tail()` digunakan untuk melihat data terbawah (default = 5)

In [64]:
# df.head(3)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 750-67-8428 to 849-09-3807
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   Branch                   1000 non-null   category      
 1   City                     1000 non-null   category      
 2   Customer type            1000 non-null   category      
 3   Gender                   1000 non-null   category      
 4   Product line             1000 non-null   category      
 5   Unit price               1000 non-null   float64       
 6   Quantity                 1000 non-null   int64         
 7   Tax 5%                   1000 non-null   float64       
 8   Total                    1000 non-null   float64       
 9   Date                     1000 non-null   datetime64[ns]
 10  Time                     1000 non-null   datetime64[ns]
 11  Payment                  1000 non-null   category      
 12  cogs                  

In [65]:
df.head(3)

Branch       City Customer type  Gender            Product line  \
Invoice ID                                                                    
750-67-8428      A     Yangon        Member  Female       Health and beauty   
226-31-3081      C  Naypyitaw        Normal  Female  Electronic accessories   
631-41-3108      A     Yangon        Normal    Male      Home and lifestyle   

             Unit price  Quantity   Tax 5%     Total       Date  \
Invoice ID                                                        
750-67-8428       74.69         7  26.1415  548.9715 2019-01-05   
226-31-3081       15.28         5   3.8200   80.2200 2019-03-08   
631-41-3108       46.33         7  16.2155  340.5255 2019-03-03   

                           Time      Payment      cogs  \
Invoice ID                                               
750-67-8428 2024-09-22 13:08:00      Ewallet  475.7753   
226-31-3081 2024-09-22 10:29:00         Cash   69.5240   
631-41-3108 2024-09-22 13:23:00  Credit card  295.1221   

             gross margin percentage  gross income  Rating  Year  Month  \
Invoice ID                                                                
750-67-8428                  9.89011       47.0547     9.1  2019      1   
226-31-3081                  9.89011        6.8760     9.6  2019      3   
631-41-3108                  9.89011       29.1879     7.4  2019      3   

                  Day  Day of week  
Invoice ID                          
750-67-8428  Saturday            5  
226-31-3081    Friday            4  
631-41-3108    Sunday            6

In [66]:
df.tail(3)

Branch    City Customer type  Gender         Product line  \
Invoice ID                                                              
727-02-1313      A  Yangon        Member    Male   Food and beverages   
347-56-2442      A  Yangon        Normal    Male   Home and lifestyle   
849-09-3807      A  Yangon        Member  Female  Fashion accessories   

             Unit price  Quantity  Tax 5%    Total       Date  \
Invoice ID                                                      
727-02-1313       31.84         1   1.592   33.432 2019-02-09   
347-56-2442       65.82         1   3.291   69.111 2019-02-22   
849-09-3807       88.34         7  30.919  649.299 2019-02-18   

                           Time Payment      cogs  gross margin percentage  \
Invoice ID                                                                   
727-02-1313 2024-09-22 13:22:00    Cash   28.9744                  9.89011   
347-56-2442 2024-09-22 15:33:00    Cash   59.8962                  9.89011   
849-09-3807 2024-09-22 13:28:00    Cash  562.7258                  9.89011   

             gross income  Rating  Year  Month       Day  Day of week  
Invoice ID                                                             
727-02-1313        2.8656     7.7  2019      2  Saturday            5  
347-56-2442        5.9238     4.1  2019      2    Friday            4  
849-09-3807       55.6542     6.6  2019      2    Monday            0

In [67]:
# df.tail(2)
df.tail(2)

Branch    City Customer type  Gender         Product line  \
Invoice ID                                                              
347-56-2442      A  Yangon        Normal    Male   Home and lifestyle   
849-09-3807      A  Yangon        Member  Female  Fashion accessories   

             Unit price  Quantity  Tax 5%    Total       Date  \
Invoice ID                                                      
347-56-2442       65.82         1   3.291   69.111 2019-02-22   
849-09-3807       88.34         7  30.919  649.299 2019-02-18   

                           Time Payment      cogs  gross margin percentage  \
Invoice ID                                                                   
347-56-2442 2024-09-22 15:33:00    Cash   59.8962                  9.89011   
849-09-3807 2024-09-22 13:28:00    Cash  562.7258                  9.89011   

             gross income  Rating  Year  Month     Day  Day of week  
Invoice ID                                                           
347-56-2442        5.9238     4.1  2019      2  Friday            4  
849-09-3807       55.6542     6.6  2019      2  Monday            0

#### 2. `.describe()`

Method `.describe()` merupakan sebuah method yang dapat memberikan ringkasan statistik deskriptif dari suatu kumpulan data. 

**Statistik deskriptif** adalah metode statistik yang digunakan untuk meringkas, mendeskripsikan, dan menyajikan data sehingga dapat dengan mudah dipahami dan dianalisis. 

**Komponen Utama Statistik Deskriptif:**

##### 1. **Ukuran Pemusatan (Measures of Central Tendency)** -> memberikan informasi tentang nilai tengah atau pusat dari data. 
- **Mean (Rata-rata)**: Jumlah semua nilai dibagi dengan jumlah nilai.  $$Mean = \frac{\sum_{i=1}^n x_i}{n}$$
- **Median (Median)**: Nilai tengah dari data yang diurutkan. Jika jumlah nilai genap, median adalah rata-rata dari dua nilai tengah.
- **Mode (Modus)**: Nilai yang paling sering muncul dalam dataset.


##### 2. **Ukuran Posisi (Measures of Position)** -> Ukuran ini memberikan informasi tentang posisi nilai-nilai dalam data relatif terhadap yang lain.

- **Quartiles (Kuartil)**: Tipe khusus dari ukuran posisi yang membagi data menjadi empat bagian yang sama, jadi ada kuartil 1 (25%), 2 (50% atau median), 3 (75%).
- **Decile (Desil)**: Tipe khusus dari ukuran posisi yang membagi data menjadi sepuluh bagian yang sama, jadi ada desil 1 (10%), 2(20%), 3(30%), 4(40%), 5(50%)...9(90%).
- **Percentiles (Persentil)**: Tipe khusus dari ukuran posisi yang membagi data menjadi seratus bagian yang sama, jadi ada persentil 1,2,3........99. 


##### 3. **Ukuran Dispersi (Measures of Dispersion)** -> memberikan informasi seberapa tersebar nilai-nilai dalam data.
- **Range (Rentang)**: Selisih antara nilai maksimum dan nilai minimum. $$Range = \text{Max} - \text{Min}$$
- **Variance (Variansi)**: Rata-rata kuadrat dari selisih setiap nilai terhadap mean. Mengukur seberapa besar nilai dalam data tersebar di sekitar mean. $$Variance = \frac{\sum (x_i - \mu)^2}{n}$$
- **Standard Deviation (Standar Deviasi)**: Akar kuadrat dari variansi. Ini memberikan ukuran seberapa banyak data bervariasi dari mean. $$Standard Deviation = \sqrt{\text{Variance}}$$
- **Interquartile Range (Rentang Antar Kuartil, IQR)**: Selisih antara kuartil pertama (Q1) dan kuartil ketiga (Q3). Mengukur seberapa besar nilai tersebar di sekitar median.
$$IQR = Q3 - Q1$$



**Parameter `desribe(include = '....')`** 
- None: Semua tipe data yang kompatibel
- 'all': Semua kolom, tanpa memandang tipe
- 'number': Hanya kolom numerik
- 'object': Hanya kolom objek (string)
- 'category': Hanya kolom kategorikal
- 'datetime': Hanya kolom datetime

**describe(include='number')**
- count : jumlah data.
- mean : nilai rata-rata dari data.
- std : nilai standar deviasi dari data.
- min : nilai terkecil dari data.
- 25% : nilai kuartil 1 dari data.
- 50% : nilai kuartil 2 atau median dari data
- 75% : nilai kuartil 3 dari data.
- max : nilai terbesar dari data. 

In [68]:
# code df.
df.describe()

Unit price     Quantity       Tax 5%        Total  \
count  1000.000000  1000.000000  1000.000000  1000.000000   
mean     55.672130     5.510000    15.379369   322.966749   
min      10.080000     1.000000     0.508500    10.678500   
25%      32.875000     3.000000     5.924875   124.422375   
50%      55.230000     5.000000    12.088000   253.848000   
75%      77.935000     8.000000    22.445250   471.350250   
max      99.960000    10.000000    49.650000  1042.650000   
std      26.494628     2.923431    11.708825   245.885335   

                             Date                        Time         cogs  \
count                        1000                        1000  1000.000000   
mean   2019-02-14 00:05:45.600000  2024-09-22 15:24:41.880000   279.904516   
min           2019-01-01 00:00:00         2024-09-22 10:00:00     9.254700   
25%           2019-01-24 00:00:00         2024-09-22 12:43:00   107.832725   
50%           2019-02-13 00:00:00         2024-09-22 15:19:00   220.001600   
75%           2019-03-08 00:00:00         2024-09-22 18:15:00   408.503550   
max           2019-03-30 00:00:00         2024-09-22 20:59:00   903.630000   
std                           NaN                         NaN   213.100624   

       gross margin percentage  gross income      Rating    Year        Month  \
count             1.000000e+03   1000.000000  1000.00000  1000.0  1000.000000   
mean              9.890110e+00     27.682864     6.97270  2019.0     1.993000   
min               9.890110e+00      0.915300     4.00000  2019.0     1.000000   
25%               9.890110e+00     10.664775     5.50000  2019.0     1.000000   
50%               9.890110e+00     21.758400     7.00000  2019.0     2.000000   
75%               9.890110e+00     40.401450     8.50000  2019.0     3.000000   
max               9.890110e+00     89.370000    10.00000  2019.0     3.000000   
std               1.167029e-14     21.075886     1.71858     0.0     0.835254   

       Day of week  
count  1000.000000  
mean      3.032000  
min       0.000000  
25%       1.000000  
50%       3.000000  
75%       5.000000  
max       6.000000  
std       1.973543

> Insight : 

1. Unit price tertinggi adalah sebesar $99.96
2. Unit price terendah adalah sebesar $10.08
3. Standar deviasi kuantitas adalah sebesar 2.923431

**df.describe(include='category')**
- count : jumlah keseluruhan kolom data.
- unique : nilai unik dari kumpulan data.
- top : nilai yang paling sering muncul (modus). 
- freq : jumlah frekuensi dari nilai modus. 

In [69]:
# code
df.describe(include='category')

Branch    City Customer type  Gender         Product line  Payment  \
count    1000    1000          1000    1000                 1000     1000   
unique      3       3             2       2                    6        3   
top         A  Yangon        Member  Female  Fashion accessories  Ewallet   
freq      340     340           501     501                  178      345   

             Day  
count       1000  
unique         7  
top     Saturday  
freq         164

> Insight : 

1. Cabang yang paling sering terjadi transaksi adalah cabang A
2. Product line yang paling sering terjadi transaksi adalah fashion accessories sebesar 178 transaksi
3. Hari yang paling serign terjadi transaksi adalah hari Sabtu

#### 3. `.dtypes`

Atribut yang digunakan untuk mengecek tipe data. 

In [70]:
# df.dtypes
df.dtypes

Branch                           category
City                             category
Customer type                    category
Gender                           category
Product line                     category
Unit price                        float64
Quantity                            int64
Tax 5%                            float64
Total                             float64
Date                       datetime64[ns]
Time                       datetime64[ns]
Payment                          category
cogs                              float64
gross margin percentage           float64
gross income                      float64
Rating                            float64
Year                                int32
Month                               int32
Day                              category
Day of week                         int32
dtype: object

#### 4. `info()`

Method yang memberikan kumpulan berbagai informasi, jumlah kolom dan rincian, jumlah baris, tipe data, penggunaan memori dsb.

In [71]:
# df.info()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 750-67-8428 to 849-09-3807
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   Branch                   1000 non-null   category      
 1   City                     1000 non-null   category      
 2   Customer type            1000 non-null   category      
 3   Gender                   1000 non-null   category      
 4   Product line             1000 non-null   category      
 5   Unit price               1000 non-null   float64       
 6   Quantity                 1000 non-null   int64         
 7   Tax 5%                   1000 non-null   float64       
 8   Total                    1000 non-null   float64       
 9   Date                     1000 non-null   datetime64[ns]
 10  Time                     1000 non-null   datetime64[ns]
 11  Payment                  1000 non-null   category      
 12  cogs                  

## G. Data Wrangling dan Exploratory Data Analysis (EDA) - Intermediate

### 1 `value_counts()`

Melalui method `value_counts(ascending = False)`, kita dapat menghitung jumlah baris pada setiap category dalam 1 kolom (nilai frekuensi/kemunculan data), dan defaultnya akan diurutkan secara descending (besar ke kecil). 

parameter tambahan : 
- `sort=False`: untuk mencegah pengurutan apapun sehingga hanya berdasarkan indeks. 
- `ascending=True`: Mengurutkan nilai dari kecil ke besar / menaik.

In [72]:
# code
df['Branch'].value_counts()

Branch
A    340
B    332
C    328
Name: count, dtype: int64

In [73]:
df['Branch'].value_counts(ascending=True)

Branch
C    328
B    332
A    340
Name: count, dtype: int64

In [74]:
# code
df['Branch'].value_counts(sort=False)

Branch
A    340
B    332
C    328
Name: count, dtype: int64

In [75]:
#baris = index, kolom = index_col

In [76]:
pd.DataFrame(df['Branch'].value_counts(ascending=True))

count
Branch       
C         328
B         332
A         340

In [77]:
pd.DataFrame(df['Branch'].value_counts(sort=False))

count
Branch       
A         340
B         332
C         328

### 2. `pd.crosstab()`

Melalui method `pd.crosstab()`, kita dapat menghitung frekuensi suatu data (fungsi dari value_counts()) dan juga agregasi data. 

```
pd.crosstab(index=....,
            columns=....,
            values=....,
            aggfunc=agg_function)
```

Parameter : 
- `index` : kolom yang akan menjadi baris (axis 0)
- `columns` : kolom yang akan menjadi kolom (axis 1)
- `values` : kolom yang dijadikan landasan menerapkan aggfunc (*optional*)
- `aggfunc` : agregasi fungsi, sebuah fungsi yang akan dieksekusi (*optional*)

Contoh `aggfunc`:
- `mean` : nilai rata-rata
- `median` : nilai tengah
- `min` : nilai minimum 
- `max` : nilai maksimum
- `count` : jumlah kemunculan baris (tabel frekuensi)
- `sum` : jumlah suatu nilai 

##### Cabang manakah yang memiliki transaksi terbesar dan terkecil ❓

In [78]:
df.head()

Branch       City Customer type  Gender            Product line  \
Invoice ID                                                                    
750-67-8428      A     Yangon        Member  Female       Health and beauty   
226-31-3081      C  Naypyitaw        Normal  Female  Electronic accessories   
631-41-3108      A     Yangon        Normal    Male      Home and lifestyle   
123-19-1176      A     Yangon        Member    Male       Health and beauty   
373-73-7910      A     Yangon        Normal    Male       Sports and travel   

             Unit price  Quantity   Tax 5%     Total       Date  \
Invoice ID                                                        
750-67-8428       74.69         7  26.1415  548.9715 2019-01-05   
226-31-3081       15.28         5   3.8200   80.2200 2019-03-08   
631-41-3108       46.33         7  16.2155  340.5255 2019-03-03   
123-19-1176       58.22         8  23.2880  489.0480 2019-01-27   
373-73-7910       86.31         7  30.2085  634.3785 2019-02-08   

                           Time      Payment      cogs  \
Invoice ID                                               
750-67-8428 2024-09-22 13:08:00      Ewallet  475.7753   
226-31-3081 2024-09-22 10:29:00         Cash   69.5240   
631-41-3108 2024-09-22 13:23:00  Credit card  295.1221   
123-19-1176 2024-09-22 20:33:00      Ewallet  423.8416   
373-73-7910 2024-09-22 10:37:00      Ewallet  549.7947   

             gross margin percentage  gross income  Rating  Year  Month  \
Invoice ID                                                                
750-67-8428                  9.89011       47.0547     9.1  2019      1   
226-31-3081                  9.89011        6.8760     9.6  2019      3   
631-41-3108                  9.89011       29.1879     7.4  2019      3   
123-19-1176                  9.89011       41.9184     8.4  2019      1   
373-73-7910                  9.89011       54.3753     5.3  2019      2   

                  Day  Day of week  
Invoice ID                          
750-67-8428  Saturday            5  
226-31-3081    Friday            4  
631-41-3108    Sunday            6  
123-19-1176    Sunday            6  
373-73-7910    Friday            4

In [79]:
# Hanya tabel frekuensi 
pd.crosstab(
    index=df['Branch'],
    columns='Frequency'
)

col_0   Frequency
Branch           
A             340
B             332
C             328

Menambahkan method `sort_values()` untuk mengurukan data frame berdasarkan kolom tertentu. 

- `by` : di isi dengan nama kolom
- `ascending` : secara default = True (diurutkan berdasarkan nilai terkecil ke terbesar).

In [80]:
# Hanya tabel frekuensi + diurutkan
pd.crosstab(
    index=df['Product line'],
    columns='Frequency'
)

col_0                   Frequency
Product line                     
Electronic accessories        170
Fashion accessories           178
Food and beverages            174
Health and beauty             152
Home and lifestyle            160
Sports and travel             166

In [81]:
pd.crosstab(
    index=df['Product line'],
    columns='Frequency'
).sort_values(by='Frequency',ascending=False)

col_0                   Frequency
Product line                     
Fashion accessories           178
Food and beverages            174
Electronic accessories        170
Sports and travel             166
Home and lifestyle            160
Health and beauty             152

> 1. Product line **fashion accessories** merupakan product line dengan transaksi terbesar
2. Product line **health and beauty** merupakan product line dengan transaksi terkecil

##### Pada hari apa yang memiliki transaksi tertinggi dan terendah❓

In [82]:
# code
df.head()

Branch       City Customer type  Gender            Product line  \
Invoice ID                                                                    
750-67-8428      A     Yangon        Member  Female       Health and beauty   
226-31-3081      C  Naypyitaw        Normal  Female  Electronic accessories   
631-41-3108      A     Yangon        Normal    Male      Home and lifestyle   
123-19-1176      A     Yangon        Member    Male       Health and beauty   
373-73-7910      A     Yangon        Normal    Male       Sports and travel   

             Unit price  Quantity   Tax 5%     Total       Date  \
Invoice ID                                                        
750-67-8428       74.69         7  26.1415  548.9715 2019-01-05   
226-31-3081       15.28         5   3.8200   80.2200 2019-03-08   
631-41-3108       46.33         7  16.2155  340.5255 2019-03-03   
123-19-1176       58.22         8  23.2880  489.0480 2019-01-27   
373-73-7910       86.31         7  30.2085  634.3785 2019-02-08   

                           Time      Payment      cogs  \
Invoice ID                                               
750-67-8428 2024-09-22 13:08:00      Ewallet  475.7753   
226-31-3081 2024-09-22 10:29:00         Cash   69.5240   
631-41-3108 2024-09-22 13:23:00  Credit card  295.1221   
123-19-1176 2024-09-22 20:33:00      Ewallet  423.8416   
373-73-7910 2024-09-22 10:37:00      Ewallet  549.7947   

             gross margin percentage  gross income  Rating  Year  Month  \
Invoice ID                                                                
750-67-8428                  9.89011       47.0547     9.1  2019      1   
226-31-3081                  9.89011        6.8760     9.6  2019      3   
631-41-3108                  9.89011       29.1879     7.4  2019      3   
123-19-1176                  9.89011       41.9184     8.4  2019      1   
373-73-7910                  9.89011       54.3753     5.3  2019      2   

                  Day  Day of week  
Invoice ID                          
750-67-8428  Saturday            5  
226-31-3081    Friday            4  
631-41-3108    Sunday            6  
123-19-1176    Sunday            6  
373-73-7910    Friday            4

In [83]:
pd.crosstab(
    index=df['Day'],
    columns='Frequency'
).sort_values(by='Frequency',ascending=False)

col_0      Frequency
Day                 
Saturday         164
Tuesday          158
Wednesday        143
Friday           139
Thursday         138
Sunday           133
Monday           125

> JAWABANNYA : Pada hari Sabtu terdapat jumlah transaksi tertinggi sebesar 164, sedangkan pada hari Senin terdapat jumlah transkasi terendah sebesar 125.

##### Produk line apa yang paling tinggi transaksinya di setiap cabang ❓

In [84]:
# mengetahui frekuensi kombinasi 
pd.crosstab(
    index=df['Branch'],
    columns=df['Product line']
)

Product line  Electronic accessories  Fashion accessories  Food and beverages  \
Branch                                                                          
A                                 60                   51                  58   
B                                 55                   62                  50   
C                                 55                   65                  66   

Product line  Health and beauty  Home and lifestyle  Sports and travel  
Branch                                                                  
A                            47                  65                 59  
B                            53                  50                 62  
C                            52                  45                 45

**Margins** 

Dapat menambahkan parameter `margins=True` agar menampilkan total frekuensi transaksi di setiap baris dan kolomnya.

In [85]:
# mengetahui frekuensi kombinasi + margins
pd.crosstab(
    index=df['Branch'],
    columns=df['Product line'],
    margins=True
)

Product line  Electronic accessories  Fashion accessories  Food and beverages  \
Branch                                                                          
A                                 60                   51                  58   
B                                 55                   62                  50   
C                                 55                   65                  66   
All                              170                  178                 174   

Product line  Health and beauty  Home and lifestyle  Sports and travel   All  
Branch                                                                        
A                            47                  65                 59   340  
B                            53                  50                 62   332  
C                            52                  45                 45   328  
All                         152                 160                166  1000

> JAWABANNYA : 
1. Product line yang paling tinggi transaksinya di cabang A  adalah `Home and lifestyle`.
2. Product line yang paling tinggi transaksinya di cabang B adalah `Fashion accessories` dan `Sports and travel`.
3. Product line yang paling tinggi transaksinya di cabang C adalah `Fashion accesssories`.

##### Kota apa yang memiliki nilai `gross_income` tertinggi dan Terendah❓

In [86]:
# Membuat tabel agregasi
pd.crosstab(
    index=df['City'],
    columns=df['Month'],
    values=df['gross income'],
    aggfunc='sum'
)

Month              1          2          3
City                                      
Mandalay   3186.5193  2950.6518  2965.4865
Naypyitaw  3465.8298  2822.9985  3188.4894
Yangon     3315.5253  2559.4389  3227.9247

In [87]:
pd.crosstab(
    index=df['City'],
    columns=df['Month'],
    values=df['gross income'],
    aggfunc='sum',
    margins=True
    )

Month              1          2          3         All
City                                                  
Mandalay   3186.5193  2950.6518  2965.4865   9102.6576
Naypyitaw  3465.8298  2822.9985  3188.4894   9477.3177
Yangon     3315.5253  2559.4389  3227.9247   9102.8889
All        9967.8744  8333.0892  9381.9006  27682.8642

> JAWABANNYA :
1. Pada bulan 1 (Januari), nilai `gross income` tertinggi diperoleh di kota `Naypyitaw` dan terendah di kota `Mandalay`.
2. Pada bulan 2 (Februari), nilai `gross income` tertinggi diperoleh di kota `Mandalay` dan terendah di kota `Yangon`.
3. Pada bulan 3 (Maret), nilai `gross income` tertinggi diperoleh di kota `Yangon` dan terendah di kota `Mandalay`.


### 3. `groupby()`

Operasi `groupby()` digunakan untuk mengelompokkan suatu kumpulan data berdasarkan hal-hal tertentu. Fungsi agregasi yang dapat digunakan `sum()`, `mean()`, `count()`, `median()`, `min()`, dan `max()`.

In [88]:
df.head()

Branch       City Customer type  Gender            Product line  \
Invoice ID                                                                    
750-67-8428      A     Yangon        Member  Female       Health and beauty   
226-31-3081      C  Naypyitaw        Normal  Female  Electronic accessories   
631-41-3108      A     Yangon        Normal    Male      Home and lifestyle   
123-19-1176      A     Yangon        Member    Male       Health and beauty   
373-73-7910      A     Yangon        Normal    Male       Sports and travel   

             Unit price  Quantity   Tax 5%     Total       Date  \
Invoice ID                                                        
750-67-8428       74.69         7  26.1415  548.9715 2019-01-05   
226-31-3081       15.28         5   3.8200   80.2200 2019-03-08   
631-41-3108       46.33         7  16.2155  340.5255 2019-03-03   
123-19-1176       58.22         8  23.2880  489.0480 2019-01-27   
373-73-7910       86.31         7  30.2085  634.3785 2019-02-08   

                           Time      Payment      cogs  \
Invoice ID                                               
750-67-8428 2024-09-22 13:08:00      Ewallet  475.7753   
226-31-3081 2024-09-22 10:29:00         Cash   69.5240   
631-41-3108 2024-09-22 13:23:00  Credit card  295.1221   
123-19-1176 2024-09-22 20:33:00      Ewallet  423.8416   
373-73-7910 2024-09-22 10:37:00      Ewallet  549.7947   

             gross margin percentage  gross income  Rating  Year  Month  \
Invoice ID                                                                
750-67-8428                  9.89011       47.0547     9.1  2019      1   
226-31-3081                  9.89011        6.8760     9.6  2019      3   
631-41-3108                  9.89011       29.1879     7.4  2019      3   
123-19-1176                  9.89011       41.9184     8.4  2019      1   
373-73-7910                  9.89011       54.3753     5.3  2019      2   

                  Day  Day of week  
Invoice ID                          
750-67-8428  Saturday            5  
226-31-3081    Friday            4  
631-41-3108    Sunday            6  
123-19-1176    Sunday            6  
373-73-7910    Friday            4

In [89]:
# Mengelompokkan cuma berdasarkan 1 hal - Total sales di setiap kota
df.groupby("City")['Total'].mean()


C:\Users\Naresya Wijaya\AppData\Local\Temp\ipykernel_16724\4129432505.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("City")['Total'].mean()


City
Mandalay     319.872506
Naypyitaw    337.099715
Yangon       312.354031
Name: Total, dtype: float64

In [90]:
kota dengan rata rata total sales terbesar adalah naypytaw

SyntaxError: invalid syntax (37681310.py, line 1)

In [91]:
# Mengelompokkan berdasarkan > 1 hal rata rata total sales kota dan setiap genre
df.groupby(["City","Gender"])['Total'].mean()


C:\Users\Naresya Wijaya\AppData\Local\Temp\ipykernel_16724\1095807966.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["City","Gender"])['Total'].mean()


City       Gender
Mandalay   Female    326.717870
           Male      313.349276
Naypyitaw  Female    346.547545
           Male      325.888290
Yangon     Female    330.864391
           Male      295.705047
Name: Total, dtype: float64

kota yangon gender male memiliki rata rata penjualan terkecil diantara semua kota dan gender

##### Berapa total `gross income` setiap bulan di masing-masing kota❓

In [92]:
# code
df.groupby(
    ["Month", "City"]
)['gross income'].sum()

C:\Users\Naresya Wijaya\AppData\Local\Temp\ipykernel_16724\3658886446.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(


Month  City     
1      Mandalay     3186.5193
       Naypyitaw    3465.8298
       Yangon       3315.5253
2      Mandalay     2950.6518
       Naypyitaw    2822.9985
       Yangon       2559.4389
3      Mandalay     2965.4865
       Naypyitaw    3188.4894
       Yangon       3227.9247
Name: gross income, dtype: float64

## H. Indexing and Subsetting Data 

Indexing dan Subsetting Data merupakan sebuah proses memilih sebagian data yang hanya diperlukan (baris atau kolom tertentu) dalam proses analisa data.

Prose ini dapat dilakukan dengan menggunakan library `pandas` sebagai berikut :

1. `.iloc[]` operator
2. `select_dtypes()`
3. `.drop()`
4. conditional subsetting. 

In [93]:
latihan_sub = pd.read_csv("data\sales.csv")
latihan_sub.head(3)

Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428      A     Yangon        Member  Female   
1  226-31-3081      C  Naypyitaw        Normal  Female   
2  631-41-3108      A     Yangon        Normal    Male   

             Product line  Unit price  Quantity   Tax 5%     Total      Date  \
0       Health and beauty       74.69         7  26.1415  548.9715  1/5/2019   
1  Electronic accessories       15.28         5   3.8200   80.2200  3/8/2019   
2      Home and lifestyle       46.33         7  16.2155  340.5255  3/3/2019   

    Time      Payment      cogs  gross margin percentage  gross income  Rating  
0  13:08      Ewallet  475.7753                  9.89011       47.0547     9.1  
1  10:29         Cash   69.5240                  9.89011        6.8760     9.6  
2  13:23  Credit card  295.1221                  9.89011       29.1879     7.4

### H.1. `.iloc`

`.iloc`/**(index)** merujuk pada urutan **index baris atau kolom** sehingga berupa bilangan bulat. `.iloc` juga menerapkan konsep python berhitung  (*Zero-based indexing*). 

Contoh :

`df.iloc[index baris, index kolom]`

`df.iloc[0:10, 7:9]` artinya hanya menampilkan baris urutan ke 0 hingga ke 9, dan kolom ke 7 dan 8. 

In [94]:
# Hanya menampilkan baris dan kolom
latihan_sub.iloc[0:10, 7:9]


Quantity   Tax 5%
0         7  26.1415
1         5   3.8200
2         7  16.2155
3         8  23.2880
4         7  30.2085
5         7  29.8865
6         6  20.6520
7        10  36.7800
8         2   3.6260
9         3   8.2260

### H.2. `select_dtypes()`

Method `select_dtypes()` berfungsi untuk memilih kolom berdasarkan tipe data yang dipilih. `select_dtypes()` memiliki 2 parameter yang digunakan :
- `include` : yang termasuk kolom tipe data dipilih akan ditampilkan kolomnya.
- `exclude` : yang tidak termasuk / yang dikecualikan maka kolom tersebut tidak ditampilkan.

Pilihan argummen : 
- `object`, `int64`, `float64`, `bool`, `datetime64`, `timedelta[ns]`, dan `category`.


In [95]:
# Hanya kolom yang termasuk tipe category yang akan di tampilkan
latihan_sub.select_dtypes(include="object")

Invoice ID Branch       City Customer type  Gender  \
0    750-67-8428      A     Yangon        Member  Female   
1    226-31-3081      C  Naypyitaw        Normal  Female   
2    631-41-3108      A     Yangon        Normal    Male   
3    123-19-1176      A     Yangon        Member    Male   
4    373-73-7910      A     Yangon        Normal    Male   
..           ...    ...        ...           ...     ...   
995  233-67-5758      C  Naypyitaw        Normal    Male   
996  303-96-2227      B   Mandalay        Normal  Female   
997  727-02-1313      A     Yangon        Member    Male   
998  347-56-2442      A     Yangon        Normal    Male   
999  849-09-3807      A     Yangon        Member  Female   

               Product line       Date   Time      Payment  
0         Health and beauty   1/5/2019  13:08      Ewallet  
1    Electronic accessories   3/8/2019  10:29         Cash  
2        Home and lifestyle   3/3/2019  13:23  Credit card  
3         Health and beauty  1/27/2019  20:33      Ewallet  
4         Sports and travel   2/8/2019  10:37      Ewallet  
..                      ...        ...    ...          ...  
995       Health and beauty  1/29/2019  13:46      Ewallet  
996      Home and lifestyle   3/2/2019  17:16      Ewallet  
997      Food and beverages   2/9/2019  13:22         Cash  
998      Home and lifestyle  2/22/2019  15:33         Cash  
999     Fashion accessories  2/18/2019  13:28         Cash  

[1000 rows x 9 columns]

In [96]:
df.select_dtypes(include="category")

Branch       City Customer type  Gender            Product line  \
Invoice ID                                                                    
750-67-8428      A     Yangon        Member  Female       Health and beauty   
226-31-3081      C  Naypyitaw        Normal  Female  Electronic accessories   
631-41-3108      A     Yangon        Normal    Male      Home and lifestyle   
123-19-1176      A     Yangon        Member    Male       Health and beauty   
373-73-7910      A     Yangon        Normal    Male       Sports and travel   
...            ...        ...           ...     ...                     ...   
233-67-5758      C  Naypyitaw        Normal    Male       Health and beauty   
303-96-2227      B   Mandalay        Normal  Female      Home and lifestyle   
727-02-1313      A     Yangon        Member    Male      Food and beverages   
347-56-2442      A     Yangon        Normal    Male      Home and lifestyle   
849-09-3807      A     Yangon        Member  Female     Fashion accessories   

                 Payment       Day  
Invoice ID                          
750-67-8428      Ewallet  Saturday  
226-31-3081         Cash    Friday  
631-41-3108  Credit card    Sunday  
123-19-1176      Ewallet    Sunday  
373-73-7910      Ewallet    Friday  
...                  ...       ...  
233-67-5758      Ewallet   Tuesday  
303-96-2227      Ewallet  Saturday  
727-02-1313         Cash  Saturday  
347-56-2442         Cash    Friday  
849-09-3807         Cash    Monday  

[1000 rows x 7 columns]

In [97]:
# Selain kolom tipe category, maka akan di tampilkan
latihan_sub.select_dtypes(exclude="object")

Unit price  Quantity   Tax 5%      Total      cogs  \
0         74.69         7  26.1415   548.9715  475.7753   
1         15.28         5   3.8200    80.2200   69.5240   
2         46.33         7  16.2155   340.5255  295.1221   
3         58.22         8  23.2880   489.0480  423.8416   
4         86.31         7  30.2085   634.3785  549.7947   
..          ...       ...      ...        ...       ...   
995       40.35         1   2.0175    42.3675   36.7185   
996       97.38        10  48.6900  1022.4900  886.1580   
997       31.84         1   1.5920    33.4320   28.9744   
998       65.82         1   3.2910    69.1110   59.8962   
999       88.34         7  30.9190   649.2990  562.7258   

     gross margin percentage  gross income  Rating  
0                    9.89011       47.0547     9.1  
1                    9.89011        6.8760     9.6  
2                    9.89011       29.1879     7.4  
3                    9.89011       41.9184     8.4  
4                    9.89011       54.3753     5.3  
..                       ...           ...     ...  
995                  9.89011        3.6315     6.2  
996                  9.89011       87.6420     4.4  
997                  9.89011        2.8656     7.7  
998                  9.89011        5.9238     4.1  
999                  9.89011       55.6542     6.6  

[1000 rows x 8 columns]

In [98]:
# Memilih kolom lebih dari satu tipe data
latihan_sub.select_dtypes(include=["object","int64","Float64"])

Invoice ID Branch       City Customer type  Gender  \
0    750-67-8428      A     Yangon        Member  Female   
1    226-31-3081      C  Naypyitaw        Normal  Female   
2    631-41-3108      A     Yangon        Normal    Male   
3    123-19-1176      A     Yangon        Member    Male   
4    373-73-7910      A     Yangon        Normal    Male   
..           ...    ...        ...           ...     ...   
995  233-67-5758      C  Naypyitaw        Normal    Male   
996  303-96-2227      B   Mandalay        Normal  Female   
997  727-02-1313      A     Yangon        Member    Male   
998  347-56-2442      A     Yangon        Normal    Male   
999  849-09-3807      A     Yangon        Member  Female   

               Product line  Unit price  Quantity   Tax 5%      Total  \
0         Health and beauty       74.69         7  26.1415   548.9715   
1    Electronic accessories       15.28         5   3.8200    80.2200   
2        Home and lifestyle       46.33         7  16.2155   340.5255   
3         Health and beauty       58.22         8  23.2880   489.0480   
4         Sports and travel       86.31         7  30.2085   634.3785   
..                      ...         ...       ...      ...        ...   
995       Health and beauty       40.35         1   2.0175    42.3675   
996      Home and lifestyle       97.38        10  48.6900  1022.4900   
997      Food and beverages       31.84         1   1.5920    33.4320   
998      Home and lifestyle       65.82         1   3.2910    69.1110   
999     Fashion accessories       88.34         7  30.9190   649.2990   

          Date   Time      Payment      cogs  gross margin percentage  \
0     1/5/2019  13:08      Ewallet  475.7753                  9.89011   
1     3/8/2019  10:29         Cash   69.5240                  9.89011   
2     3/3/2019  13:23  Credit card  295.1221                  9.89011   
3    1/27/2019  20:33      Ewallet  423.8416                  9.89011   
4     2/8/2019  10:37      Ewallet  549.7947                  9.89011   
..         ...    ...          ...       ...                      ...   
995  1/29/2019  13:46      Ewallet   36.7185                  9.89011   
996   3/2/2019  17:16      Ewallet  886.1580                  9.89011   
997   2/9/2019  13:22         Cash   28.9744                  9.89011   
998  2/22/2019  15:33         Cash   59.8962                  9.89011   
999  2/18/2019  13:28         Cash  562.7258                  9.89011   

     gross income  Rating  
0         47.0547     9.1  
1          6.8760     9.6  
2         29.1879     7.4  
3         41.9184     8.4  
4         54.3753     5.3  
..            ...     ...  
995        3.6315     6.2  
996       87.6420     4.4  
997        2.8656     7.7  
998        5.9238     4.1  
999       55.6542     6.6  

[1000 rows x 17 columns]

### H.3. `.drop()`

Method `drop()` berfungsi untuk memotong atau membuang baris atau kolom. Secara default method ini akan menghapus baris (index) dan dapat menghapus kolom menggunakan parameter (columns). 

In [99]:
df.head()

Branch       City Customer type  Gender            Product line  \
Invoice ID                                                                    
750-67-8428      A     Yangon        Member  Female       Health and beauty   
226-31-3081      C  Naypyitaw        Normal  Female  Electronic accessories   
631-41-3108      A     Yangon        Normal    Male      Home and lifestyle   
123-19-1176      A     Yangon        Member    Male       Health and beauty   
373-73-7910      A     Yangon        Normal    Male       Sports and travel   

             Unit price  Quantity   Tax 5%     Total       Date  \
Invoice ID                                                        
750-67-8428       74.69         7  26.1415  548.9715 2019-01-05   
226-31-3081       15.28         5   3.8200   80.2200 2019-03-08   
631-41-3108       46.33         7  16.2155  340.5255 2019-03-03   
123-19-1176       58.22         8  23.2880  489.0480 2019-01-27   
373-73-7910       86.31         7  30.2085  634.3785 2019-02-08   

                           Time      Payment      cogs  \
Invoice ID                                               
750-67-8428 2024-09-22 13:08:00      Ewallet  475.7753   
226-31-3081 2024-09-22 10:29:00         Cash   69.5240   
631-41-3108 2024-09-22 13:23:00  Credit card  295.1221   
123-19-1176 2024-09-22 20:33:00      Ewallet  423.8416   
373-73-7910 2024-09-22 10:37:00      Ewallet  549.7947   

             gross margin percentage  gross income  Rating  Year  Month  \
Invoice ID                                                                
750-67-8428                  9.89011       47.0547     9.1  2019      1   
226-31-3081                  9.89011        6.8760     9.6  2019      3   
631-41-3108                  9.89011       29.1879     7.4  2019      3   
123-19-1176                  9.89011       41.9184     8.4  2019      1   
373-73-7910                  9.89011       54.3753     5.3  2019      2   

                  Day  Day of week  
Invoice ID                          
750-67-8428  Saturday            5  
226-31-3081    Friday            4  
631-41-3108    Sunday            6  
123-19-1176    Sunday            6  
373-73-7910    Friday            4

In [101]:
# Menghapus baris pertama
df.drop(0)

KeyError: '[0] not found in axis'

In [100]:
# Hapus baris ke 1 (226-31-3081) dan 2 (631-41-3108) yang baru 
df.drop(1,2)

TypeError: DataFrame.drop() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
# Bakal error ketika ingin menghapus 'City' karena default dikira baris


In [103]:
# df.drop(columns='City')
df.drop(columns='City')

Branch Customer type  Gender            Product line  Unit price  \
Invoice ID                                                                     
750-67-8428      A        Member  Female       Health and beauty       74.69   
226-31-3081      C        Normal  Female  Electronic accessories       15.28   
631-41-3108      A        Normal    Male      Home and lifestyle       46.33   
123-19-1176      A        Member    Male       Health and beauty       58.22   
373-73-7910      A        Normal    Male       Sports and travel       86.31   
...            ...           ...     ...                     ...         ...   
233-67-5758      C        Normal    Male       Health and beauty       40.35   
303-96-2227      B        Normal  Female      Home and lifestyle       97.38   
727-02-1313      A        Member    Male      Food and beverages       31.84   
347-56-2442      A        Normal    Male      Home and lifestyle       65.82   
849-09-3807      A        Member  Female     Fashion accessories       88.34   

             Quantity   Tax 5%      Total       Date                Time  \
Invoice ID                                                                 
750-67-8428         7  26.1415   548.9715 2019-01-05 2024-09-22 13:08:00   
226-31-3081         5   3.8200    80.2200 2019-03-08 2024-09-22 10:29:00   
631-41-3108         7  16.2155   340.5255 2019-03-03 2024-09-22 13:23:00   
123-19-1176         8  23.2880   489.0480 2019-01-27 2024-09-22 20:33:00   
373-73-7910         7  30.2085   634.3785 2019-02-08 2024-09-22 10:37:00   
...               ...      ...        ...        ...                 ...   
233-67-5758         1   2.0175    42.3675 2019-01-29 2024-09-22 13:46:00   
303-96-2227        10  48.6900  1022.4900 2019-03-02 2024-09-22 17:16:00   
727-02-1313         1   1.5920    33.4320 2019-02-09 2024-09-22 13:22:00   
347-56-2442         1   3.2910    69.1110 2019-02-22 2024-09-22 15:33:00   
849-09-3807         7  30.9190   649.2990 2019-02-18 2024-09-22 13:28:00   

                 Payment      cogs  gross margin percentage  gross income  \
Invoice ID                                                                  
750-67-8428      Ewallet  475.7753                  9.89011       47.0547   
226-31-3081         Cash   69.5240                  9.89011        6.8760   
631-41-3108  Credit card  295.1221                  9.89011       29.1879   
123-19-1176      Ewallet  423.8416                  9.89011       41.9184   
373-73-7910      Ewallet  549.7947                  9.89011       54.3753   
...                  ...       ...                      ...           ...   
233-67-5758      Ewallet   36.7185                  9.89011        3.6315   
303-96-2227      Ewallet  886.1580                  9.89011       87.6420   
727-02-1313         Cash   28.9744                  9.89011        2.8656   
347-56-2442         Cash   59.8962                  9.89011        5.9238   
849-09-3807         Cash  562.7258                  9.89011       55.6542   

             Rating  Year  Month       Day  Day of week  
Invoice ID                                               
750-67-8428     9.1  2019      1  Saturday            5  
226-31-3081     9.6  2019      3    Friday            4  
631-41-3108     7.4  2019      3    Sunday            6  
123-19-1176     8.4  2019      1    Sunday            6  
373-73-7910     5.3  2019      2    Friday            4  
...             ...   ...    ...       ...          ...  
233-67-5758     6.2  2019      1   Tuesday            1  
303-96-2227     4.4  2019      3  Saturday            5  
727-02-1313     7.7  2019      2  Saturday            5  
347-56-2442     4.1  2019      2    Friday            4  
849-09-3807     6.6  2019      2    Monday            0  

[1000 rows x 19 columns]

In [102]:
# df.drop(columns=['Branch', 'City', 'Customer type'])
df.drop(columns=['Branch','City', 'Customer type'])

Gender            Product line  Unit price  Quantity   Tax 5%  \
Invoice ID                                                                   
750-67-8428  Female       Health and beauty       74.69         7  26.1415   
226-31-3081  Female  Electronic accessories       15.28         5   3.8200   
631-41-3108    Male      Home and lifestyle       46.33         7  16.2155   
123-19-1176    Male       Health and beauty       58.22         8  23.2880   
373-73-7910    Male       Sports and travel       86.31         7  30.2085   
...             ...                     ...         ...       ...      ...   
233-67-5758    Male       Health and beauty       40.35         1   2.0175   
303-96-2227  Female      Home and lifestyle       97.38        10  48.6900   
727-02-1313    Male      Food and beverages       31.84         1   1.5920   
347-56-2442    Male      Home and lifestyle       65.82         1   3.2910   
849-09-3807  Female     Fashion accessories       88.34         7  30.9190   

                 Total       Date                Time      Payment      cogs  \
Invoice ID                                                                     
750-67-8428   548.9715 2019-01-05 2024-09-22 13:08:00      Ewallet  475.7753   
226-31-3081    80.2200 2019-03-08 2024-09-22 10:29:00         Cash   69.5240   
631-41-3108   340.5255 2019-03-03 2024-09-22 13:23:00  Credit card  295.1221   
123-19-1176   489.0480 2019-01-27 2024-09-22 20:33:00      Ewallet  423.8416   
373-73-7910   634.3785 2019-02-08 2024-09-22 10:37:00      Ewallet  549.7947   
...                ...        ...                 ...          ...       ...   
233-67-5758    42.3675 2019-01-29 2024-09-22 13:46:00      Ewallet   36.7185   
303-96-2227  1022.4900 2019-03-02 2024-09-22 17:16:00      Ewallet  886.1580   
727-02-1313    33.4320 2019-02-09 2024-09-22 13:22:00         Cash   28.9744   
347-56-2442    69.1110 2019-02-22 2024-09-22 15:33:00         Cash   59.8962   
849-09-3807   649.2990 2019-02-18 2024-09-22 13:28:00         Cash  562.7258   

             gross margin percentage  gross income  Rating  Year  Month  \
Invoice ID                                                                
750-67-8428                  9.89011       47.0547     9.1  2019      1   
226-31-3081                  9.89011        6.8760     9.6  2019      3   
631-41-3108                  9.89011       29.1879     7.4  2019      3   
123-19-1176                  9.89011       41.9184     8.4  2019      1   
373-73-7910                  9.89011       54.3753     5.3  2019      2   
...                              ...           ...     ...   ...    ...   
233-67-5758                  9.89011        3.6315     6.2  2019      1   
303-96-2227                  9.89011       87.6420     4.4  2019      3   
727-02-1313                  9.89011        2.8656     7.7  2019      2   
347-56-2442                  9.89011        5.9238     4.1  2019      2   
849-09-3807                  9.89011       55.6542     6.6  2019      2   

                  Day  Day of week  
Invoice ID                          
750-67-8428  Saturday            5  
226-31-3081    Friday            4  
631-41-3108    Sunday            6  
123-19-1176    Sunday            6  
373-73-7910    Friday            4  
...               ...          ...  
233-67-5758   Tuesday            1  
303-96-2227  Saturday            5  
727-02-1313  Saturday            5  
347-56-2442    Friday            4  
849-09-3807    Monday            0  

[1000 rows x 17 columns]

Catatan :

Ketika menggunakan method `.drop()` maka belum akan mengubah data kita (mengurangi data) karena belum di assigment. Perubahan dapat dilakukan dengan meng-assign perubahan :

- `df = df.drop(columns=['Branch', 'City', 'Customer type'])`

atau menambahkan parameter `inplace=True` : 

- `df.drop(columns=['Branch', 'City', 'Customer type'], inplace=True)`

### H.4.  Conditional Subsetting

Subsetting dapat dilakukan berdasarkan kondisi tertentu. Kondisi ini dapat berupa operator pembanding seperti `==`, `!=`, `>`, `>=`, `<`, `<=`. 

- Contohnya : `latihan_sub[latihan_sub['nama kolom']] <operator pembanding> value`

##### Berapa banyak transaksi di kota Naypyitaw dan menghasilkan keuntungan lebih atau sama dengan 50❓

In [104]:
# Definisikan kondisi
Nay=df['City']=="Naypyitaw"
lebih_sama_50=df['gross income']>=50

df[Nay&lebih_sama_50]

Branch       City Customer type  Gender            Product line  \
Invoice ID                                                                    
699-14-3026      C  Naypyitaw        Normal    Male  Electronic accessories   
315-22-5665      C  Naypyitaw        Normal  Female      Home and lifestyle   
228-96-1411      C  Naypyitaw        Member  Female      Food and beverages   
574-22-5561      C  Naypyitaw        Member  Female     Fashion accessories   
326-78-5178      C  Naypyitaw        Member    Male      Food and beverages   
...            ...        ...           ...     ...                     ...   
887-42-0517      C  Naypyitaw        Normal  Female       Sports and travel   
702-83-5291      C  Naypyitaw        Member    Male     Fashion accessories   
148-41-7930      C  Naypyitaw        Normal    Male       Health and beauty   
189-40-5216      C  Naypyitaw        Normal    Male  Electronic accessories   
267-62-7380      C  Naypyitaw        Member    Male  Electronic accessories   

             Unit price  Quantity   Tax 5%     Total       Date  \
Invoice ID                                                        
699-14-3026       85.39         7  29.8865  627.6165 2019-03-25   
315-22-5665       73.56        10  36.7800  772.3800 2019-02-24   
228-96-1411       98.70         8  39.4800  829.0800 2019-03-04   
574-22-5561       82.63        10  41.3150  867.6150 2019-03-19   
326-78-5178       91.40         7  31.9900  671.7900 2019-02-03   
...                 ...       ...      ...       ...        ...   
887-42-0517       83.14         7  29.0990  611.0790 2019-01-10   
702-83-5291       99.82         9  44.9190  943.2990 2019-03-27   
148-41-7930       99.96         7  34.9860  734.7060 2019-01-23   
189-40-5216       96.37         7  33.7295  708.3195 2019-01-09   
267-62-7380       82.34        10  41.1700  864.5700 2019-03-29   

                           Time      Payment      cogs  \
Invoice ID                                               
699-14-3026 2024-09-22 18:30:00      Ewallet  543.9343   
315-22-5665 2024-09-22 11:38:00      Ewallet  669.3960   
228-96-1411 2024-09-22 20:39:00         Cash  718.5360   
574-22-5561 2024-09-22 17:08:00      Ewallet  751.9330   
326-78-5178 2024-09-22 10:19:00         Cash  582.2180   
...                         ...          ...       ...   
887-42-0517 2024-09-22 10:31:00  Credit card  529.6018   
702-83-5291 2024-09-22 10:43:00         Cash  817.5258   
148-41-7930 2024-09-22 10:33:00         Cash  636.7452   
189-40-5216 2024-09-22 11:40:00         Cash  613.8769   
267-62-7380 2024-09-22 19:12:00      Ewallet  749.2940   

             gross margin percentage  gross income  Rating  Year  Month  \
Invoice ID                                                                
699-14-3026                  9.89011       53.7957     4.1  2019      3   
315-22-5665                  9.89011       66.2040     8.0  2019      2   
228-96-1411                  9.89011       71.0640     7.6  2019      3   
574-22-5561                  9.89011       74.3670     7.9  2019      3   
326-78-5178                  9.89011       57.5820     9.5  2019      2   
...                              ...           ...     ...   ...    ...   
887-42-0517                  9.89011       52.3782     6.6  2019      1   
702-83-5291                  9.89011       80.8542     6.6  2019      3   
148-41-7930                  9.89011       62.9748     6.1  2019      1   
189-40-5216                  9.89011       60.7131     6.0  2019      1   
267-62-7380                  9.89011       74.1060     4.3  2019      3   

                   Day  Day of week  
Invoice ID                           
699-14-3026     Monday            0  
315-22-5665     Sunday            6  
228-96-1411     Monday            0  
574-22-5561    Tuesday            1  
326-78-5178     Sunday            6  
...                ...          ...  
887-42-0517   Thursday            3  
702-83-5291  Wednesday            2  
1

> transaksi di kota naypyitaw dan keuntungan lebih dari 50 adalah 63 transaksi

In [105]:
#Berapa banyak transaksi di kota Yangon dan menghasilkan keuntungan (`gross_income`) lebih atau sama dengan 75
Yan=df['City']=="Yangon"
lebih_sama_75=df['gross income']>=75

df[Yan&lebih_sama_75]

Branch    City Customer type  Gender            Product line  \
Invoice ID                                                                 
704-48-3927      A  Yangon        Member    Male  Electronic accessories   
687-47-8271      A  Yangon        Normal    Male     Fashion accessories   
325-77-6186      A  Yangon        Member  Female      Home and lifestyle   
827-77-7633      A  Yangon        Normal    Male       Sports and travel   
805-86-0265      A  Yangon        Normal    Male      Home and lifestyle   
384-59-6655      A  Yangon        Member  Female      Food and beverages   
139-32-4183      A  Yangon        Member  Female       Sports and travel   

             Unit price  Quantity   Tax 5%      Total       Date  \
Invoice ID                                                         
704-48-3927       88.67        10  44.3350   931.0350 2019-01-12   
687-47-8271       98.98        10  49.4900  1039.2900 2019-02-08   
325-77-6186       90.65        10  45.3250   951.8250 2019-03-08   
827-77-7633       98.09         9  44.1405   926.9505 2019-02-17   
805-86-0265       93.96         9  42.2820   887.9220 2019-03-20   
384-59-6655       98.66         9  44.3970   932.3370 2019-02-19   
139-32-4183       97.48         9  43.8660   921.1860 2019-03-14   

                           Time      Payment      cogs  \
Invoice ID                                               
704-48-3927 2024-09-22 14:50:00      Ewallet  806.8970   
687-47-8271 2024-09-22 16:20:00  Credit card  900.7180   
325-77-6186 2024-09-22 10:53:00      Ewallet  824.9150   
827-77-7633 2024-09-22 19:41:00         Cash  803.3571   
805-86-0265 2024-09-22 11:32:00         Cash  769.5324   
384-59-6655 2024-09-22 15:07:00         Cash  808.0254   
139-32-4183 2024-09-22 14:19:00      Ewallet  798.3612   

             gross margin percentage  gross income  Rating  Year  Month  \
Invoice ID                                                                
704-48-3927                  9.89011       79.8030     7.3  2019      1   
687-47-8271                  9.89011       89.0820     8.7  2019      2   
325-77-6186                  9.89011       81.5850     7.3  2019      3   
827-77-7633                  9.89011       79.4529     9.3  2019      2   
805-86-0265                  9.89011       76.1076     9.8  2019      3   
384-59-6655                  9.89011       79.9146     8.4  2019      2   
139-32-4183                  9.89011       78.9588     7.4  2019      3   

                   Day  Day of week  
Invoice ID                           
704-48-3927   Saturday            5  
687-47-8271     Friday            4  
325-77-6186     Friday            4  
827-77-7633     Sunday            6  
805-86-0265  Wednesday            2  
384-59-6655    Tuesday            1  
139-32-4183   Thursday            3

##### Berapa banyak transaksi pelanggan Member yang memberikan rating kurang dari atau sama dengan 5❓

In [106]:
#kondisi
Member = df['customer type'] == "Member"
rating_kurang_sama5 = df['Rating'] <= 5


#menghitung
len(df[Member & rating_kurang_sama5])

print(jumlah)
print(persentase)

KeyError: 'customer type'

> banyak transaksi pelanggan member yang memberi rating kurang dari atau sama dengan 5 sebanyak 98 transaksi = 9,8%

##### Berapa banyak transaksi pelanggan Member dan Payment Cash yang memberikan rating lebih dari atau sama dengan 5❓

In [107]:
df.head()

Branch       City Customer type  Gender            Product line  \
Invoice ID                                                                    
750-67-8428      A     Yangon        Member  Female       Health and beauty   
226-31-3081      C  Naypyitaw        Normal  Female  Electronic accessories   
631-41-3108      A     Yangon        Normal    Male      Home and lifestyle   
123-19-1176      A     Yangon        Member    Male       Health and beauty   
373-73-7910      A     Yangon        Normal    Male       Sports and travel   

             Unit price  Quantity   Tax 5%     Total       Date  \
Invoice ID                                                        
750-67-8428       74.69         7  26.1415  548.9715 2019-01-05   
226-31-3081       15.28         5   3.8200   80.2200 2019-03-08   
631-41-3108       46.33         7  16.2155  340.5255 2019-03-03   
123-19-1176       58.22         8  23.2880  489.0480 2019-01-27   
373-73-7910       86.31         7  30.2085  634.3785 2019-02-08   

                           Time      Payment      cogs  \
Invoice ID                                               
750-67-8428 2024-09-22 13:08:00      Ewallet  475.7753   
226-31-3081 2024-09-22 10:29:00         Cash   69.5240   
631-41-3108 2024-09-22 13:23:00  Credit card  295.1221   
123-19-1176 2024-09-22 20:33:00      Ewallet  423.8416   
373-73-7910 2024-09-22 10:37:00      Ewallet  549.7947   

             gross margin percentage  gross income  Rating  Year  Month  \
Invoice ID                                                                
750-67-8428                  9.89011       47.0547     9.1  2019      1   
226-31-3081                  9.89011        6.8760     9.6  2019      3   
631-41-3108                  9.89011       29.1879     7.4  2019      3   
123-19-1176                  9.89011       41.9184     8.4  2019      1   
373-73-7910                  9.89011       54.3753     5.3  2019      2   

                  Day  Day of week  
Invoice ID                          
750-67-8428  Saturday            5  
226-31-3081    Friday            4  
631-41-3108    Sunday            6  
123-19-1176    Sunday            6  
373-73-7910    Friday            4

In [108]:
# Kondisi
Member=df['customer type']=="Member"
Cash=df['Payment']=="Cash"
lebih_sama_5=df['Rating'] >= 5

len(df[Member&Cash&lebih_sama_5])

# Persentase pembayaran yang dilakukan secara tunai


# Menghitung persentase pelanggan cash yang merasa puas


KeyError: 'customer type'

In [ ]:
# Hasil 
transaksi pelanggan member dan payment cadh yang memberi rating lebih dari atau = 5 adalah 139 transaksi


## I. Introduction to Data Visualization

Visualisasi (*Visualization*) merupakan suatu cara untuk menyajikan data dalam bentuk visual agar mempermudah kita dan orang lain memahami data. Poin utama dari visualisasi data adalah bagaimana kita bisa menyampaikan sebuah informasi dengan efektif (*insight*) sehingga berguna dalam pembuatan keputusan apapun. 

Visualisasi data memiliki tiga kategori 
1. Univariate Visualization
2. Bivariate Visualization
3. Multivariate Visualization

Pemilihan berbagai jenis atau bentuk visualisasi data sangat bergantung pada kondisi data yang akan disajikan, [Guidance Penentuan Jenis Visualisasi](https://www.data-to-viz.com/). 

In [115]:
import seaborn as sns
import matplotlib.pyplot as plt

### 1. Univariate Visualization
Bentuk visualisasi data yang memvisualisasikan hanya satu variabel dalam suatu waktu.

#### Histogram Chart

Histogram adalah jenis grafik yang menampilkan distribusi frekuensi dari satu variabel kontinyu (*Satu Data Numerik*). Penggunaan :
- Menganalisis distribusi atau sebaran data numerik.
- Mengidentifikasi pola seperti distribusi normal, bimodal, atau skewness.
- Mengetahui frekuensi data dalam interval tertentu.

##### Hari apakah yang memiliki Jumlah Transaksi Terbesar dan Terkecil❓

In [ ]:
# Menentukan ukuran canvas


# Mengisi visualisasi dengan data


# Menambahkan atribut pendukung


# Tampilkan



> Kesimpulan 

...

### 2. Bivariate Visualization
Bentuk visualisasi data yang memvisualisasikan hanya dua variabel dalam suatu waktu. Terdapat beberapa tipe kombinasi yang dapat terjadi dari gabungan dua variabel : 
1. Data Kategorikal (Nilai Berulang) dan Numerik (Nilai Angka)
2. Data Numerik (Nilai Angka) dan Numerik (Nilai Angka)
3. Data Kategorikal (Nilai Berulang) dan Kategorik (Nilai Berulang) 

#### 2.A Bar Chart

Bar chart adalah jenis grafik yang menggunakan batang untuk mewakili nilai atau frekuensi dari kategori data tertentu. Batang-batang tersebut terpisah dan tidak bersebelahan satu sama lain, menunjukkan perbandingan antar kategori yang berbeda. Penggunaan :
- Membandingkan nilai atau frekuensi antar kategori yang berbeda.
- Menganalisis data diskrit atau kategorikal.

**Note :**
- Histogram: Cocok untuk menganalisis distribusi data numerik, melihat frekuensi dalam interval, dan memahami pola penyebaran data.
- Bar Chart: Ideal untuk membandingkan nilai di antara beberapa kategori atau kelompok data yang berbeda.

##### Cabang manakah yang memiliki Total Nilai Penjualan Terbesar ❓

In [ ]:
# Agregasi Data


In [ ]:
# Menentukan ukuran canvas


# Mengisi visualisasi dengan data


# Menambahkan atribut pendukung


# Tampilkan


##### Product Line apa yang memberikan gross income terbesar dan terkecil ❓

In [ ]:
# Agregasi Data


In [ ]:
# Visualisasi data - Horizontal


> Kesimpulan

...

#### 2.B Line Chart

Diagram garis adalah grafik yang menggunakan garis untuk menghubungkan titik-titik data yang biasanya diambil pada interval yang berurutan. Grafik ini digunakan untuk menunjukkan bagaimana nilai suatu variabel berubah seiring waktu atau kondisi lainnya. Penggunaan : 
- Menampilkan tren data dari waktu ke waktu.
- Melihat pola, misalnya kenaikan atau penurunan dalam data.
- Memantau perubahan data harian, mingguan, bulanan, atau tahunan.

##### Tren mingguan gross income di setiap kota ❓

In [ ]:
# Ekstrak fitur mingguan 


# Menghitung Kota Yangon


# Menghitung Kota Naypyitaw


# Menghitung Kota Mandalay


In [ ]:
# Plot untuk setiap kota


#### 2.C Boxplot Chart

Boxplot adalah grafik yang menunjukkan distribusi data berdasarkan lima angka ringkasan: minimum, kuartil pertama (Q1), median, kuartil ketiga (Q3), dan maksimum. Biasanya digunakan untuk melihat rentang, sebaran dan outlier dalam data. Penggunaan : 
- Menilai distribusi data, termasuk outlier atau pencilan.
- Membandingkan distribusi antar kelompok atau kategori.
- Memahami rentang interkuartil dan sebaran data.

In [ ]:
# Membuat boxplot


In [ ]:


# Data contoh untuk boxplot



# Data contoh untuk scatter plot



# Menampilkan plot



#### 2.D Scatter Chart

Diagram pencar adalah grafik yang menggunakan titik-titik untuk mewakili nilai dua variabel yang berbeda. Titik-titik ini kemudian dipetakan pada sumbu x dan y untuk melihat apakah ada hubungan atau korelasi antara dua variabel. Penggunaan:
- Menganalisis hubungan atau korelasi antara dua variabel.
- Mengidentifikasi pola, tren, atau anomali dalam data.
- Melihat distribusi dan kepadatan data.

In [ ]:
# Membuat scatter plot



#### 2.E Heatmap Chart

Heatmap adalah grafik yang menggunakan skema warna untuk mewakili nilai atau frekuensi data dalam matriks atau tabel. Warna-warna yang berbeda menunjukkan intensitas atau nilai yang berbeda dari data. Penggunaan:
- Memvisualisasikan korelasi antara dua set data.
- Menyajikan data dalam bentuk matriks yang mudah dipahami secara visual.

In [ ]:
# Persiapan data


In [ ]:
# Membuat heatmap


### 3. Multivariate Visualization
Bentuk visualisasi data yang memvisualisasikan lebih dari dua variabel dalam suatu waktu.



In [ ]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

# Data contoh: Tiga variabel (x, y, z)
np.random.seed(0)
x = np.random.rand(100)
y = np.random.rand(100)
z = np.random.rand(100) * 100

# Membuat 3D scatter plot
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(x, y, z, s=50, c=z, cmap='viridis', alpha=0.8)
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
ax.set_title('3D Scatter Plot')
plt.show()

Beberapa opsi visualisasi di Python yang dapat dieksplorasi lebih lanjut :

- `matplotlib`: semua elemen pada visualisasi dapat dikustomisasi, namun membutuhkan code yang lebih panjang. [Dokumentasi Matplotlib](https://matplotlib.org/3.2.2/tutorials/index.html). 
- `seaborn`: dikembangkan dari `matplotlib`, lebih sedikit yang dapat dikustomisasi namun lebih mudah. [Dokumentasi Seaborn](https://seaborn.pydata.org/introduction.html).
- `plotly`: plot interaktif serta kompatibilitas dengan bahasa lain yang tinggi. [Dokumentasi Plotly](https://plotly.com/python/).

## J. Interactive Visualization

Visualisasi interaktif digunakan untuk memberikan kesan yang menarik dan insight lebih baik karena kita dapat melihat informasi detail langsung, tinggal di klik. Kita akan membuat visualisasi interaktif menggunakan [`plotly`](https://plotly.com/python/).

In [ ]:
import plotly
import plotly.express as px

### 1. Bagaimana Performa (Total, Quantity, Gross Income) Sales Perusahaan dalam Rentang Tertentu?
Jadi ntr ada 3 opsi yang bisa dilihat dalam rentang waktu tertentu (Total, Quantity, dan Gross Income). Baru di rekapkan total nilainya / keseluruhan atau total per hari berapa.

In [ ]:
# Persiapan Data


In [ ]:
# plot

### 2. Bagaimana Performa (Total, Quantity, Gross Income) pada Setiap Product Line?

In [ ]:
# Persiapan Data


In [ ]:
# plot


### 3. Bagaimana Persebaran Total Penjualan dalam Hari maupun Jam Tertentu?

In [ ]:
# Feature Engineering kolom Hour

# df['Hour'] = 

In [ ]:
# Urutkan nama-nama hari

'''
ordered_days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
                'Friday','Saturday','Sunday']

df['Day of Week'] = pd.Categorical(df['Day of Week'], 
                                   categories=ordered_days,
                                   ordered=True)
                                   
'''

"\nordered_days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',\n                'Friday','Saturday','Sunday']\n\ndf['Day of Week'] = pd.Categorical(df['Day of Week'], \n                                   categories=ordered_days,\n                                   ordered=True)\n                                   \n"

In [ ]:
# Persiapan data

### 4. Bagaimana Perbandingan Gender Pembeli di Setiap Product Line?

In [ ]:
# persiapan data


In [ ]:
# melt()

In [ ]:
# Plot

In [ ]:
# df = df.rename(columns={'gross income':'Gross Income'})         
# df = df.rename(columns={'cogs':'COGS'})

## Dashboard - Streamlit

![Alt text](asset/Dashboard.png)

In [109]:
# save pickle
df.to_pickle('data_sales_dash.pkl')

In [110]:
# coba baca ulang
df = pd.read_pickle('data_sales_dash.pkl')

In [112]:
# cek tipe data
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 750-67-8428 to 849-09-3807
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   Branch                   1000 non-null   category      
 1   City                     1000 non-null   category      
 2   Customer type            1000 non-null   category      
 3   Gender                   1000 non-null   category      
 4   Product line             1000 non-null   category      
 5   Unit price               1000 non-null   float64       
 6   Quantity                 1000 non-null   int64         
 7   Tax 5%                   1000 non-null   float64       
 8   Total                    1000 non-null   float64       
 9   Date                     1000 non-null   datetime64[ns]
 10  Time                     1000 non-null   datetime64[ns]
 11  Payment                  1000 non-null   category      
 12  cogs                  

Save to pickel pas persiapan ke pembuatan dashboard untuk mengamankan format. 

## Final Project

Dear Rekan-Rekan,

Selamat atas keberhasilannya menyelesaikan Bootcamp Data Science. Dalam rangka untuk mendapatkan sertifkat kegiatan yang sudah diikuti dan meningkatkan kemampuan rekan-rekan dalam mengimplementasikan ilmu yang didapatkan di kelas, Rekan-rekan dapat mengumpulkan hasil latihan berdasarkan tahapan yang sudah kita pelajari di kelas. Adapun untuk referensi pengerjaan, Bapak dan Ibu dapat mengacu pada materi di kelas. Berikut ketentuannya : 
- Anda di wajibkan untuk menampilkan minimal 2 **visualisasi data interaktif** - bebas (line, bar, scatter dsb).
- Anda di wajibkan untuk menerapkan minimal 1 input data dalam visualisasi data interaktif.
- Terakhir anda diwajibkan untuk mendeploy projek anda melalui akun Github. 

Sumber Data yang dapat digunakan :
- [Vehicle Sales Data](https://www.kaggle.com/datasets/syedanwarafridi/vehicle-sales-data)
- [NYC Property Sales](https://www.kaggle.com/datasets/new-york-city/nyc-property-sales)
- Atau data lainnya yang sesuai dengan ketertarikan anda, bisa explorasi di [Kaggle](kaggle.com), dsb.



Mohon untuk mengumpulkan hasil LBB paling lambat pada hari Minggu, 08 September 2024, 11:59 WIB, dengan melampirkan link dashboard anda.

Selamat mengeksplorasi !

**Note :**
- Materi yang dipelajari selama 4 hari ini memang masih sangat terbatas tetapi sangat baik sebagai bagian proses untuk pengembangan diri lebih lanjut.
- Anda diharapkan dapat belajar secara aktif melalui pembuatan berbagai project baru dengan mencari data dari berbagai sumber [Kaggle](kaggle.com), [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/v), dsb.
- Anda juga dapat mengembangkan skill anda ke ranah pengolahan data yang lebih dalam (Machine Learning, Artificial Intelligence dsb).

# Reference

https://medium.com/@gfakhira9/to-period-909ee90ce6c1

https://www.geeksforgeeks.org/what-is-univariate-bivariate-multivariate-analysis-in-data-visualisation/